### ISSUE TITLE
Incorrect labeling of y-axis when plotting different data products

### ISSUE THREAD

**Issue by rebekah9969** [lightkurve/lightkurve#1001]
I am noticing some issues with the y-axis labels on some of my plots. Below is the code that I am using in addition to the plots. 
`search_lc = lk.search_lightcurve("V1357 Cyg")
search_lc

spoc_lcf = search_lc[0].download()
tess_spoc_lcf = search_lc[1].download()
qlp_lcf = search_lc[2].download()

ax = spoc_lcf.plot(label="spoc_lcf")
tess_spoc_lcf.plot(ax=ax, label="tess_spoc_lcf")
qlp_lcf.plot(ax=ax, label="qlp_lcf")`

The above code produces a plot with the y-axis label "Normalized Flux" This is not the case - it should actually be something like "Flux [incompatible units]". 

<img width="792" alt="Screen Shot 2021-03-17 at 2 14 00 PM" src="https://user-images.githubusercontent.com/17503131/111521914-1545ad80-8730-11eb-8954-f21d4edc2c04.png">

Additional code 

`ax = spoc_lcf.plot(column="sap_flux", normalize=True, label="spoc_lcf")

tess_spoc_lcf.plot(ax=ax, column="sap_flux", normalize=True, label="tess_spoc_lcf")

qlp_lcf.plot(ax=ax, column="sap_flux", label="qlp_lcf")`

Then causes the following plot, which should say something about "Normalized SAP Flux" not sap_flux.

The QLA sap flux is automatically normalized as a default.

<img width="759" alt="Screen Shot 2021-03-17 at 2 50 57 PM" src="https://user-images.githubusercontent.com/17503131/111522125-5211a480-8730-11eb-9f79-bb134adfff4c.png">

**Comment by barentsen** [comment]
@rebekah9969 I believe I addressed this issue over in #1002.

Would you be willing to review the PR and the screenshots posted there to confirm that it is a good fix for this issue?

Thank you!!
