### ISSUE TITLE
`LightCurveCollection` repr does not provide the entries in the collection in order

### ISSUE THREAD

**Issue by christinahedges** [lightkurve/lightkurve#1006]
This might be expected behavior, but `LightCurveCollection` (and presumably everything in collection) has a repr that prints the entries in the collection out of order:

![image](https://user-images.githubusercontent.com/14965634/111714890-e4d54080-880f-11eb-9d3c-89f2a199f260.png)

This actually -might- be desirable. It automatically clumps the same quarters, campaigns and sectors together to make an abbreviated repr. But it did just trip me up. 

Opening this up for discussion!

**Comment by barentsen** [comment]
I think I addressed this issue via PR #1007.  Feedback welcome!

**Comment by barentsen** [comment]
Closing this issue because PR #1007 has been merged, but additional ideas for improving LightCurveCollection remain very welcome!
