### ISSUE TITLE
Broken Hyperlinks for the "How to load and use Cotrending Basis Vectors for Kepler, K2 and TESS" tutorial

### ISSUE THREAD

**Issue by rebekah9969** [lightkurve/lightkurve#1009]
The DesignMatrix page and CBVCorrector HOWTO page hyperlinks are broken for this tutorial.
I would fix them but I do not know exactly which pages this tutorial is referring to.

**Comment by jcsmithhere** [comment]
CBV tutorial hyperlinks fixed in PR 1013

**Comment by barentsen** [comment]
Fixed because #1013 has been merged.  Thank you both!!
