### ISSUE TITLE
Campaign 1 TESS-SPOC data products appear to have 600s exposure time

### ISSUE THREAD

**Issue by warrickball** [lightkurve/lightkurve#1011]
#### Problem description

At least two stars (R Dor and R Hor) have TESS-SPOC light curves, derived from full-frame images, which the search says have a 600s exposure time. The data itself actually has a cadence of 1800s, which lines up with the 1800s cadence of full-frame images in the nominal mission.

I also realise this might not be a Lightkurve issue but rather something upstream in e.g. MAST.

#### Example

```python
import lightkurve
print(lk.search_lightcurve('R Dor', mission='TESS', author='TESS-SPOC'))
```
gives output
```
SearchResult containing 2 data products.

 #     mission     year   author  exptime target_name distance
                                     s                 arcsec 
--- -------------- ---- --------- ------- ----------- --------
  0 TESS Sector 02 2018 TESS-SPOC     600    38877693      0.0
  1 TESS Sector 03 2018 TESS-SPOC     600    38877693      0.0
```
To be fair, here's a star that looks okay in Campaign 2:
```python
import lightkurve
print(lk.search_lightcurve('T Cep', mission='TESS', author='TESS-SPOC'))
```
with output
```
SearchResult containing 2 data products.

 #     mission     year   author  exptime target_name distance
                                     s                 arcsec 
--- -------------- ---- --------- ------- ----------- --------
  0 TESS Sector 16 2019 TESS-SPOC    1800   388000857      0.0
  1 TESS Sector 17 2019 TESS-SPOC    1800   388000857      0.0
  2 TESS Sector 18 2019 TESS-SPOC    1800   388000857      0.0
  3 TESS Sector 24 2020 TESS-SPOC    1800   388000857      0.0
  4 TESS Sector 25 2020 TESS-SPOC    1800   388000857      0.0
```

#### Expected behavior

I expected the `exptime` to be 1800s for TESS's Campaign 1.

#### Environment

- Fedora 33
- lightkurve 2.0.6
- via pip 20.2.2

**Comment by barentsen** [comment]
@warrickball Thanks for reporting!

This is indeed a glitch in the meta data reported by the MAST Portal API for a set of newly-ingested TESS-SPOC light curves.

MAST is aware of the issue (via @scfleming) and will fix it! :+1:
