### ISSUE TITLE
Weird behaviour for light curves after 2.0.b3 ?

### ISSUE THREAD

**Issue by LucaNap** [lightkurve/lightkurve#1027]
Hello. I was working with 2.0.b3 a couple of days ago and everything ran smoothly, then by chance I had to change environment and installed the latest version of lightkurve available (2.0.9), which brought me a couple of issues.

```python
lc = lk.search_lightcurve(target,mission='TESS')
lc = lc.download_all().stitch()
lc = lc.remove_outliers()

flat, trend = lc.flatten(window_length=301, return_trend=True)
ax = lc.errorbar(label=target)
trend.plot(ax=ax, color='red', lw=2, label='Trend', zorder=2)
```

The above code should just download all the light curves available for the target, stitch them together, remove the outliers and plot the result with a red trend line coming from the flatten routine (note that in this case I work with "lc" and not the flatten curve). The resulting plot (2.0.b3) was OK:

![lc2 0b3](https://user-images.githubusercontent.com/74565238/114743454-fd704200-9d4c-11eb-80f9-c8c0f2947fb6.PNG)

but now with 2.0.9 I get the following:

![lc2 0 9a](https://user-images.githubusercontent.com/74565238/114743491-07924080-9d4d-11eb-94a0-e09d12f5e205.PNG)

The first issue is that there are a couple of points that shouldn't be there at all (outside of window times), and I noticed that their "quality" is something like 100000000000, so I can just filter them out with `lc[ lc.quality < 100]`. Even if I remove them, the trend line is all over the place though:

![lc2 0 9b](https://user-images.githubusercontent.com/74565238/114743776-4627fb00-9d4d-11eb-9f95-bdac75efa93f.PNG)

That being said, the overall light curve is not the "same" as the one I got from 2.0.b3 because the flux=1 is slightly different in the two versions, maybe there's an offset due to the data being "different" somehow (I won't go into detail but in practice I get two different "planet flux" result with the Starry package).

What's going on? Thank you

#### Environment

-  platform: Windows 10
-  lightkurve version: 2.0.b3 GOOD, 2.0.9 BAD
-  installation method: conda

**Comment by barentsen** [comment]
@LucaNap I'm sorry to hear you encountered this issue. Thank you for taking the time to report it!

What happened is that `search_lightcurve` was modified before the version 2.0.0 release to return *all* data products available for a given target by default, including any light curves created by alternative pipelines and/or for different cadence modes.

You are likely plotting overlapping light curves from multiple pipelines in one plot.

My recommendation is to inspect the output of `lk.search_lightcurve(target,mission='TESS')`. To restore the behavior you previously experienced with 2.0beta3, you will likely have to use `lk.search_lightcurve(target, mission='TESS', author='SPOC', exptime=120)` or something similar to that.

Does that help?

**Comment by LucaNap** [comment]
You're on point as usual! Thanks for your continuing support.
I'll keep in mind that now the author must always be specified (shouldn't the default be SPOC or somethinge else though? I don't see how anyone could use the data from all the pipelines at once).

**Comment by barentsen** [comment]
We decided to show all available data products by default to make alternative light curves easier to discover, to help users understand where a light curve comes from, and to make sure TESS FFI light curves show up when available (this wouldn't be the case if author=SPOC is the default).

You are 100% right that it doesn't make a lot of sense to stitch together light curves from different pipelines.  Perhaps a warning should be issued when light curves from different authors are downloaded or stitched together?

**Comment by LucaNap** [comment]
Fully agreed, closed!
