### ISSUE TITLE
TargetPixelFile.interact_sky() misc. enhancement

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1049]
#### Problem description
I'd like to propose a few minor enhancement on `interact_sky()` that could help to reduce an user's mental work:
1. In hover pop-in, format the x/z (the pixel row/column) as simple integers
2. Indicate the target's position
3. let users copy the GAIA ID of the hovered star. (One cannot move the mouse over to the hover tooltip to copy it, as the tooltipwill be gone).
4. (TESS-specific) provide TESS-related information when available, specifically, the TIC and TESS magnitude.

#### Example

The current `interact_sky()`:

![image](https://user-images.githubusercontent.com/250644/116918931-6b4db200-ac05-11eb-9ccf-676e46b2817d.png)

With the enhancement:

![image](https://user-images.githubusercontent.com/250644/116917567-acdd5d80-ac03-11eb-8896-1281f58953d3.png)

![image](https://user-images.githubusercontent.com/250644/116918480-cf23ab00-ac04-11eb-930a-bf69771b1beb.png)

For the copying of GAIA number: one solution is change the code so that when an user taps a star, some of the star's meta data is displayed in an adjacent text area, so that after the tooltip disappears when the user moves the mouse away, the meta data is still in the text area.

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.0.9

**Comment by barentsen** [comment]
Each of the four proposed improvements sound great to me!

Would you like me to try out the PR?

**Comment by orionlee** [comment]
Feel free to try out the PR.

**Comment by barentsen** [comment]
Good news: the enhancements proposed in this issue have been merged via #1050, and will be part of the upcoming v2.0.10 release!
