### ISSUE TITLE
Suggestion: let users customize SearchResult default display (.__repr__)

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1060]
#### Problem description

It could be convenient to let users optionally override the columns to be included in default display for SearchResult (i.e., it's `__repr__`)

My motivational use case is I find it useful to include `proposal_id` in SearchResult. 

#### Example

How the API could be tweaked to let user add `proposal_id`  to search result
```python
import lightkurve as lk

# Let users optionally override the set of columns to be displayed
lk.SearchResult.repr_columns = SearchResult.REPR_COLUMNS_DEFAULTS + ["proposal_id"]
...

lk.search_lightcurve(f"TIC364395234", mission='TESS')
```

The `proposal_id` is then then added to the display:
![image](https://user-images.githubusercontent.com/250644/118409984-08ffa300-b642-11eb-8ffe-e1484665a716.png)

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.0.9

**Comment by barentsen** [comment]
Interesting idea!

I wonder if we need to go ahead and start using Python's built-in [configparser](https://docs.python.org/3/library/configparser.html) feature (or a similar tool) to create a `lightkurve.config` object which is initialized using an optional `lightkurve.ini` file.

In this scenario, I imagine we would be able to implement this feature using something like this:

```python
from lightkurve import config
config['search']['columns'] += ["proposal_id"]
```

...which seems a bit more elegant and easier to document.

I'm not up to speed with the current best practices of adding a configuration file/system to a Python package.  One option we could explore is AstroPy's config system: https://docs.astropy.org/en/stable/config/index.html

**Comment by barentsen** [comment]
On a related note: I started wondering if and how we might adapt the existing `lightkurve.search` features to support alternative light curve databases (e.g. light curves from AAVSO, Gaia, CHEOPS, Corot, LSST, ZTF).

The existing `search_lightcurve` and `SearchResult` features are very closely intertwined with the specifics of Kepler/TESS/MAST, for example, the `proposal_id` column is very specific to the MAST API.

(I don't have a good solution to this question yet, and it shouldn't stop us from adding the feature requested here.  Just thought I'd mention it!)

**Comment by orionlee** [comment]
Given lightkurve's tight dependency on astropy, and lightkurve users are likely to be familiar with it, it might make sense to use AstroPy's config, which would take care of some of the plumbing we might need down the road, e.g., using test specific config, etc.

In that case, we might need to get some agreement with astropy. Because effectively, lightkurve would become (at least quasi officially) a astropy affiliated package. E.g, lightkurve config would be in `~/.astropy/lightkurve/lightkurve.cfg`.
