### ISSUE TITLE
tpf.interact does not display correct unit for lightcurve y-axis if lightcurve is normalized

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1061]
#### Problem description

For `tpf.interact()`, the y axis of the lightcurve is labeled to have the unit of flux (e/s), which is correct in normal usage.

However, if the user normalizes the lightcurve (by supplying `transform_func` parameter), the y axis's unit continues to be shown as the (incorrect) flux (e/s).

#### Example

When an user normalizes the lightcurve: 
```python
import lightkurve
# insert code here ...
tpf.interact(transform_func=lambda lc: lc.normalize(unit='percent'));
```

The unit of y-axis is still flux (e/s):
![image](https://user-images.githubusercontent.com/250644/118410383-043bee80-b644-11eb-9ffe-c10db776d6cb.png)

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.0.9

**Comment by barentsen** [comment]
Thank you for raising attention to this @orionlee!

It looks like the widget's `fig.yaxis.axis_label` is hard-coded in `interact.py`, which is not good!

We currently have some logic to determine a default Y axis label in the `_create_plot()` helper method of the `LightCurve` class.  I guess we could move this to a dedicated `_default_ylabel()` helper method which could then be accessed by the interact widget:

https://github.com/lightkurve/lightkurve/blob/131d5dfba39de1f736732cbed70ef544dfc558fa/src/lightkurve/lightcurve.py#L1663-L1672
