### ISSUE TITLE
Mark all tests that require external data with remote_data

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1062]
#### Problem description

Should we mark all the tests that require external data on internet with `@pytest.mark.remote_data`?

There are tests that do not appear to have external data dependency on surface, but actually do.
E.g., testing of PRF Model is not marked as remote_data, but it does rely as the implementation rely on reading calibration file hosted on stsci.edu.

As an example, when the following test run (non remotedata) failed, it is not immediately apparent that the error is a transient error due to stsci.edu not available:
https://github.com/lightkurve/lightkurve/pull/1050/checks?check_run_id=2603894239

It is apparent once one digs through the log:
```python
tests\seismology\test_stellar_estimators.py .......                      [100%]

================================== FAILURES ===================================
_______________ test_keplerprf_gradient_against_simplekeplerprf _______________

self = <urllib.request.HTTPSHandler object at 0x000001F275311790>
http_class = <class 'http.client.HTTPSConnection'>
req = <urllib.request.Request object at 0x000001F275311070>
...

tests\prf\test_prfmodel.py:79: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src\lightkurve\prf\prfmodel.py:71: in __init__
    ) = self._prepare_prf()
src\lightkurve\prf\prfmodel.py:260: in _prepare_prf
    ) = self._read_prf_calibration_file(prffile, i + 1)
src\lightkurve\prf\prfmodel.py:216: in _read_prf_calibration_file
    prf_cal_file = pyfits.open(path)    
```

**Comment by barentsen** [comment]
Yes, I'd consider the fact that this test is not marked with `@pytest.mark.remote_data` a bug!
