### ISSUE TITLE
TargetPixelFileCollection and LightCurveCollection missing in apidoc

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1068]
#### Problem description
`TargetPixelFileCollection` and `LightCurveCollection` are not included in apidoc.
They are mentioned in `download_all()`, but there is no link to the actual classes.

I suggest we can include them in "Downloading data" section of the api doc, if we don't want to create a section for them.

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.0.9

**Comment by barentsen** [comment]
Agreed!  It looks like I forgot to include these classes in the overhaul of the docs for Lightkurve v2.x
