### ISSUE TITLE
More interract_sky usability enhancement

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1081]
#### Problem description

This is a follow up on #1049. Some more suggestion on tweaking `interact_sky`
1. upon selecting a star by tapping it, show at arrow pointing at the star, rather than hiding all other stars in the view.
I don't know what the use cases are for hiding other stars. If the purpose is to make it clear the star being selected, an arrow would do. 
When I use screenshots from `interact_sky`, I repeatedly add an arrow to the screenshots, and wish `interact_sky()` would do it for me.

2. Replace the box multi-select control with box zoom.  
I am not sure how useful box multi-selecting the stars in practice. I find that at times I want to zoom in, and mistakenly thought the multi-select control as box zoom, and wish box zoom is there.

3. (Optionally), highlight aperture pixels.
If implemented, it will make it easier to cross-reference the skyview plot here with the plots from `interact` and `plot_pixels`.

---

Illustrating (1) and (2):

![image](https://user-images.githubusercontent.com/250644/120362343-d1d6f600-c2bf-11eb-9e1e-072b82f4635a.png)

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.0.9

**Comment by barentsen** [comment]
Thanks @orionlee!

I personally agree with each of the three suggestions!

@gully Do you have an opinion on box multi-select vs box zoom?

**Comment by gully** [comment]
Yikes I missed this notification from last summer, but I am glad to see the box Zoom.  Indeed the box multi-select is not relevant for `interact_sky`, simply a hold-over from the `.interact()` era.

Coincidentally, the ability to copy-and-paste the Gaia ID of a nearby source from the information window was a feature request from almost the conception of `.interact_sky`, so good moves here.
