### ISSUE TITLE
Memory leak when using lc.bin()

### ISSUE THREAD

**Issue by schristophe** [lightkurve/lightkurve#1092]
#### Problem description

When I use the bin() method with the keyword `bins`, the memory usage increases over time until it reaches 100%. The program then starts using swap memory and everything is running very slowly. The python process has to be stopped manually. This seems to happen whatever number is passed to `bins`, including negative number or a number that is > to len(lc).

![lk_memory_usage](https://user-images.githubusercontent.com/12143303/122966083-30583700-d389-11eb-9c7a-c14e4f500892.png)
(Bottom plot is memory usage. RAM in purple red, Swap memory in green)

#### Example

```python
import lightkurve as lk

d = lk.search_lightcurve('TIC382160069',cadence='short').download_all()
full_lc = d.stitch().remove_outliers()
binned_lc = full_lc.bin(bins=10000)
```

#### Possible cause

The issue seems to be caused by np.searchsorted() used here in the source code (in lightcurve.py): 

```python
   1386         if time_bin_size is None:
   1387             if bins is not None:
-> 1388                 i = len(self.time) - np.searchsorted(
   1389                     self.time, time_bin_start - 1 * u.ns
   1390                 )
```
as running the following line will result in the same problem as described above:
```python
np.searchsorted(full_lc.time, full_lc.time[0] - 1*u.ns)
```

Apparently NumPy does not like astropy's Time objects. For instance, the following code works fine and returns 0:
```python
np.searchsorted(full_lc.time.value, full_lc.time[0].value - 1e-10)
``` 

#### Expected behavior

I would expect lc.bin() to return the binned lightcurve (or raise an error if the number passed to `bins` is invalid).

#### Environment

-  platform (e.g. Linux, OSX, Windows): Linux (Ubuntu 20.04.2)
-  lightkurve version (e.g. 1.0b6): 2.0.10
- numpy version : 1.21.0
-  installation method (e.g. pip, conda, source): pip

**Comment by orionlee** [comment]
The possible cause is very likely - there were similar issues (using astropy `Time` or `Quantity` with numpy / scipy functions) that were fixed by passing raw value `.value`, just like @schristophe suggested.

**Comment by schristophe** [comment]
I encountered the same problem with the `binsize` keyword argument yesterday. There is also a call to `np.searchsorted()` here in the code:
https://github.com/lightkurve/lightkurve/blob/6175c67b4d13034ef42b436a21fe497cfdc292f9/src/lightkurve/lightcurve.py#L1395

**Comment by orionlee** [comment]
I did some research.

1. Strictly speaking, the `lc.bin()` call does not lead to memory leak, it just uses so much memory as if it is leaking. E.g., for the supplied scenario, if one calls `lc.bin()` on individual sector's lightcurves, instead of calling `lc.bin()` on a single stitched lightcurve (combining 8 sectors in the scenario), memory does not run out in my environment.

2. The underlying issue when implementation call `np.searchsorted()` with `Time`, has been identified in https://github.com/astropy/astropy/issues/10688 and fixed in astropy 4.2.

I tested it in my environment with astropy 4.2.1. The memory issue is resolved.

So a workaround would be to upgrade astropy from 4.1 to 4.2.1

**Comment by orionlee** [comment]
Action item on `Lightkurve`: we can either
1. bump astropy version from `">=4.1"` to `">=4.2"` , or
2. change `lc.bin()` codes to pass raw values rather than `Time` object to `np.searchsorted()`

**Comment by schristophe** [comment]
@orionlee Thank you for investigating this issue and making a fix!

**Comment by barentsen** [comment]
This fix will be part of the next Lightkurve release (v2.0.11).  Thanks everyone for reporting, investigating, and fixing!
