### ISSUE TITLE
Using TICA products with TessTargetPixelFile.from_fits_images

### ISSUE THREAD

**Issue by rebekah9969** [lightkurve/lightkurve#1093]
I have been trying to figure out how we can easily use the TICA products with tools available in lightkurve and also not put a huge tax on MAST. 

If you know the location of your object of interest (sector, ccd, and camera - all of which you can get using TESSpoint etc) then you can download the TICA frames via the curl scrips provided on MAST.

Next you want to cut out the region around the object from these frames and make up a TPF. 
You can do this via the following code 

```nova1 = "04:47:54.21 -10:10:43.1"
cord = SkyCoord(nova1, frame=ICRS,unit=(u.hourangle, u.deg))
fnames = np.sort(glob.glob("TICA/s0032/cam2-ccd4/*_img.fits"))
time = []

for a in range(len(fnames)):
    hdu = fits.open(fnames[a], mode='update')
    hdr = hdu[0].header 
    hdr.append(('CRVAL1P', 0.0), end=True)
    hdr.append(('CRVAL2P', 0.0), end=True)
    time.append(hdr['MIDTJD'])
    hdu.close()
    
time = np.array(time, dtype=float)

#Note if you don't append the 'CRVAL1P' and 'CRVAL2P' values then it won't work. I am not sure what the correct input is here -  but this worked for now. 

tpf = TessTargetPixelFile.from_fits_images(images_flux=fnames, position=cord, extension=0, size=(10,10))

tpf.time2 = Time(time, format='btjd')
```

Then you can define your aperture on your object of interest and create the light curve like usual using the to_lightcurve function. 
The only problem is that the times won't be correct - to get around this you can define a new lightcurveobject using 

```lc2 = lk.LightCurve(time=tpf.time2, flux = lc.flux, flux_err = lc.flux_err)```

This can then be manipulated as usual.

This is a very rough work around - but it helps if you are really trying to figure out the data.

**Comment by christinahedges** [comment]
@rebekah9969 This is a great issue, but I'm going to close this now as MAST has now added TICA to their TESSCut tool. Once astroquery updates to it's next version we'll have this functionality into lightkurve. I'm going to close this, thanks for opening!
