### ISSUE TITLE
LightCurve.normalize() - remove flux in relative units warning (or make it optional)

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1115]
#### Problem description

Use case:

I have some helpers to plot a LightCurve in some consistent style, including normalized to percentage.

```python
def plot_helper(lc):
    ...
    lc = lc.normalize(unit="percent")
    ax = lc.scatter()
    ...
```

Depending on situation, sometimes the incoming `lc` object is already normalized, but in some other units, e.g., unscaled.

In such case, `lightkurve` will emit a warning
```
 LightkurveWarning: The light curve already appears to be in relative units; `normalize()` will convert the light curve into relative units for a second time, which is probably not what you want.
```

To avoid the such warning, user would need to do additional `warnings.filterwarnings` before calling normalize.

``` python
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=lk.LightkurveWarning, message=".*in relative units.*")
        lc = lc.normalize(unit="percent")
```

### Proposal

Add an optional argument `emit_relative_units_warning=True`, to `normalize()`. Users can then conveniently do normalize without the warning in 1 line:
```python
    lc = lc.normalize(unit="percent", emit_relative_units_warning=False)
```

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.0.10

**Comment by barentsen** [comment]
I wonder why we have this warning?

If the median flux already equals 1 because the light curve was previously normalized, dividing the flux by 1 a second time doesn't seem like a big issue to me, so maybe we don't need this warning?

**Can anyone think of a scenario where normalizing a light curve multiple times causes a problem?**  If not, I'd be in favor of removing the warning, rather than adding the extra `emit_relative_units_warning` option.


Note: an alternative way to suppress the warning right now is to use:
```python
if not lc.meta.get("NORMALIZED"):
    lc = lc.normalize(unit="percent")
```

**Comment by orionlee** [comment]
@barentsen Checking the history, the relative unit warning was added in this commit https://github.com/lightkurve/lightkurve/commit/6cb3e84bdc496832ce6793956b238ccd504ad592, might it help to recall the reason of adding the warning in the first place?

**Comment by barentsen** [comment]
The commit adds 2 warnings which are definitely very important (i.e. normalizing a lightcurve where the median flux is zero or negative).

The third warning added by the commit, i.e. re-normalizing a normalized light curve, may have been added without too much thinking or justification.

Fortunately, removing a warning shouldn't change or break anyone's code.  Unless we can think of a good reason to keep the warning, I'd be happy to see it removed!  It's important to only issue warnings that are really important.  Too many unimportant warnings will make users insensitive to important warnings.
