### ISSUE TITLE
LightCurve.truncate() - let users optionally specify the column (of time) as the basis

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1116]
#### Problem description
Use case:  I have a FoldedLightCurve, `lc_f`. Occasionally, I want to plot only part of it, e.g., there are variation over time that pollutes the folded lightcurve. I want to see if the pattern holds better in a short duration.

#### Proposal

Add an optional `column` argument to `LightCurve.truncate()` function. An user can easily select part of the `FoldedLightCurve` to plot

```python
lc_f.truncate(column="time_original", 1400, 1430).scatter();
```

If PR #1105 is merged, users can also specify the truncate duration in cycle too (with the new `FoldedLightCurve.cycle`)

```python
# Want to see if the pattern holds better in the first 5 cycles 
lc_f.truncate(column="cycle", 0, 5).scatter();
```

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.0.10

**Comment by barentsen** [comment]
I think this is a good idea.  :+1:   I don't see any issues with adding an optional `column` keyword to `LightCurve.truncate()`.

Of course the user can always make a mask by hand, e.g.,
```
mask = (lc["time_original"] >= 1400) & (lc["time_original"] <= 1430)
lc = lc[mask]
```
...but it's not as fun and fluent as typing `lc.truncate(1400, 1430, column="time_original")`!
