### ISSUE TITLE
How to obtain the error ranges of the asteroseismology's key metrics (νmax and Δν) using Lightkurve's tools?

### ISSUE THREAD

**Issue by zhikai2515** [lightkurve/lightkurve#1136]
#### Problem description

    Sometimes I want to obtain a ranges of error for the asteroseismology's key metrics (νmax and Δν) of target. When I tried to search in lightKurve, I fail to find the function to output the error of νmax and Δν.
#### Example

```python
In [1]: import lightkurve
          .........
In [n]: seismology
out [n]:  Seismology(ID: KIC 10963065) - computed values:
                * numax: 2145.00 uHz (method: ACF2D)
                * deltanu: 103.11 uHz (method: ACF2D)
                * mass: 1.08 solMass (method: Uncorrected Scaling Relations)
                * radius: 1.23 solRad (method: Uncorrected Scaling Relations)
                * logg: 4.29 dex (method: Uncorrected Scaling Relations)
In [n+1]: print("Just value like 2145.00 and 103.11, no error ranges of value.")
out [n+1]: Just value like 2145.00 and 103.11, no error ranges of value.
# insert code here ...
```
#### Environment

-  platform (e.g. Linux, OSX, Windows):
-  lightkurve version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):

**Comment by barentsen** [comment]
Unfortunately Lightkurve does not currently support estimating the uncertainty of numax/deltanu.

This would be a very nice and important feature to have, but we do not currently have a plan or volunteer in place to actively work on this.

For the time being, you may want to explore asteroseismology-focused packages.  For example, [PBjam](https://pbjam.readthedocs.io) and [Pyriod](https://pyriod.readthedocs.io) jump to mind, but there are definitely others.

Please do leave a reply below if you find a good solution to this problem.  I warmly welcome and and all recommendations on how Lightkurve could implement this, or how other packages could be used to obtain this information! (/cc @ojhall94 -- any insights?)

**Comment by ojhall94** [comment]
Hi @zhikai2515!

The asteroseismic Lightkurve tools were intended as a first look at a target, not a full analyses tool, and so don't return uncertainties yet. However, there's an alternative! The techniques used in Lightkurve (the 2D ACF method) are derived from the SYD pipeline (
 Huber et al. 2009) which has recently been implemented into Python by Chontos et al. (2021). The documentation can be found here: https://pysyd.readthedocs.io/en/latest/

Applying PySYD to the data you obtain through Lightkurve should give you the answers you need!

**Comment by zhikai2515** [comment]
Hi @barentsen 
Thank you for your help! I have begun to study PBjam and Pyriod. It works for me!

**Comment by zhikai2515** [comment]
Hi @ojhall94 
Wow! A new asteroseismology's python tool with magic. I will do a small project with TESS data using pySYD. Thank you for your message!

**Comment by barentsen** [comment]
@zhikai2515 Feel free to report back with anything you learn or discover while trying these packages, in case others read this thread in the future!
