### ISSUE TITLE
Missing data for some TOIs?

### ISSUE THREAD

**Issue by avivajpeyi** [lightkurve/lightkurve#1140]
#### Problem description
I tried downloading lc data for TOI 2347 (TIC 301343785) that I think should exist (see [ExoFop Entry])
However, lightkurve's search_lightcurve does not find it! 

Am I searching for it incorrectly? 

#### Example
```python
import lightkurve as lk
search = lk.search_lightcurve(target=f"TIC 301343785", mission="TESS")
```
```
No data found for target "TIC 301343785".
ERROR:lightkurve.search:No data found for target "TIC 301343785".
```

#### Expected behavior
Example of the above working for TOI 103 (TIC 336732616)
```python
import lightkurve as lk
search = lk.search_lightcurve(target=f"TIC 336732616", mission="TESS")
```
```
>>> search
SearchResult containing 1 data products.

 #   observation  author target_name t_exptime                     productFilename                     distance
                                        sec                                                             arcsec 
--- ------------- ------ ----------- --------- ------------------------------------------------------- --------
  0 TESS Sector 1   SPOC   336732616       120 tess2018206045859-s0001-0000000336732616-0120-s_lc.fits      0.0

```

#### Environment

-  platform: OSX
-  lightkurve version: 2.0b3
-  installation method: pip

#### Plots of TOI 2347 (from ExoFop)

(https://exofop.ipac.caltech.edu/tess/target.php?id=301343785))
![Screen Shot 2021-09-10 at 5 19 42 pm](https://user-images.githubusercontent.com/15642823/132985180-acdc9bea-8718-42a5-8bda-13271954bd10.png)

#### Other tois with the same error:

- toi_3921
- toi_1160
- toi_1454
- toi_1564
- toi_2347
- toi_2561
- toi_2684
- toi_2699
- toi_2701
- toi_2717
- toi_2723
- toi_2745
- toi_3075

**Comment by avivajpeyi** [comment]
Hi! Is there something I can do to help with this? 

Im unfamiliar with lighkurve, but if you could provide some suggestions, I'm happy to try to draft a PR! :)

**Comment by barentsen** [comment]
@avivajpeyi Thank you for opening this issue, and for posting the example! :+1:

I tried executing the example a few moments ago, and I was able to see four light curves for TOI 2347:

<img width="560" alt="Screen Shot 2021-09-21 at 3 33 58 PM" src="https://user-images.githubusercontent.com/817669/134256521-b1df3d7c-b78e-4146-b6a5-331959f0d2a5.png">

Would you be willing to try this example again on your end?  My best guess is that there may have been a temporary issue with the availability of the data in the data archive, which has been resolved in the past few days.

(Side note: the first light curve found by the search operation, "DIAMANTE", is not support by Lightkurve right now.  We'll need to fix that.)

**Comment by avivajpeyi** [comment]
Thanks @barentsen 

Just checked: on repeating with `vers 2.0b3` the above still found 0 search results
![Screen Shot 2021-09-23 at 11 27 23 am](https://user-images.githubusercontent.com/15642823/134442557-8be7026f-18c3-4942-8a17-c5a7307f91f8.png)


However, upgrading to `vers 2.0.11` seems to have fixed the issue! 

![Screen Shot 2021-09-23 at 11 27 55 am](https://user-images.githubusercontent.com/15642823/134442574-6d31051b-2769-4129-9c32-ef16cdce3110.png)

**Comment by barentsen** [comment]
Oh, interesting, thanks for pointing that out!  Indeed I don't recommend using the 2.0beta versions any longer.
