### ISSUE TITLE
lightkurve.LightCurve.create_transit_mask breaks when using astropy units

### ISSUE THREAD

**Issue by decaelus** [lightkurve/lightkurve#1141]
#### Problem description

If I send an orbital period, transit time, and transit duration all with astropy units (which seems to be what the function wants), I get an error about subtracting numbers with units from numbers without units.

#### Example

```python
import lightkurve as lk
import astropy.units as u

search_result = lk.search_lightcurve("Kepler-13", mission="Kepler")
lc = search_result[3].download()

transit_mask = lc.create_transit_mask(1.7635869*u.d, (718.82552  + 2458000. - 2454833.)*u.d, 0.1359816*u.d)
```
It's line 2647 in lightcurve.py that produces the error. 

#### Expected behavior

I expected to get a transit mask array.

#### Environment

-  platform (e.g. Linux, OSX, Windows): Mac OS 11.2.3
-  lightkurve version (e.g. 1.0b6): 2.0.10
-  installation method (e.g. pip, conda, source): pip

**Comment by decaelus** [comment]
If I don't send the transit parameters using units, I don't get an error:
```python
transit_mask = lc.create_transit_mask(1.7635869, (718.82552  + 2458000. - 2454833.), 0.1359816)
```
does NOT throw an error.

**Comment by barentsen** [comment]
@decaelus Thank you for reporting this! :+1:

The issue is that the method was expecting `transit_time` to be a `Time` or a float object.  I have modified this over in #1143 to also support `Quantity` objects.

The example you posted should start working in the next release (v2.0.11).

Thanks again!
