### ISSUE TITLE
TESS-SPOC vs SPOC

### ISSUE THREAD

**Issue by eivshina** [lightkurve/lightkurve#1145]
I'm using the following line of code to download TESS data for XO-1 using the lightkurve package:
```python
result = lk.search_lightcurve('XO-1', mission = 'TESS')
```

It returns TESS-SPOC, SPOC, and QLP data products. Could you please clarify what is the difference between  TESS-SPOC and SPOC products? If you can provide a link to the paper describing each of the products, I'd appreciate it a lot. 

```python
SearchResult containing 4 data products.

 #     mission     year   author  exptime target_name distance
                                     s                 arcsec 
--- -------------- ---- --------- ------- ----------- --------
  0 TESS Sector 24 2020      SPOC     120   236312126      0.0
  1 TESS Sector 24 2020 TESS-SPOC    1800   236312126      0.0
  2 TESS Sector 24 2020       QLP    1800   236312126      0.0
  3 TESS Sector 25 2020       QLP    1800   236312126      0.0
```

Thanks,
Kate

**Comment by scfleming** [comment]
Hello, the SPOC are from the mission itself and are the formal mission products.  They are at the "short cadence" of two-minutes and based on target pixel files centered on the object.  The "TESS-SPOC" are high level science products created by a group at NASA Ames based on the full frame images.  These are thus taken at a cadence of 30-minutes or 10-minutes, depending on the Sector.  You can read about TESS-SPOC here: https://archive.stsci.edu/hlsp/tess-spoc and the Research Note that the team made: https://ui.adsabs.harvard.edu/abs/2020RNAAS...4..201C/abstract

**Comment by barentsen** [comment]
@scfleming Thanks for the fast response! 🙏 

@eivshina I'm going to close this issue for now, but feel free to respond below (or open a new issue) if you have any more questions! :+1:
