### ISSUE TITLE
Use user-defined flatten function

### ISSUE THREAD

**Issue by decaelus** [lightkurve/lightkurve#1146]
lightkurve.LightCurve.flatten works amazingly well, but it would be great if I could send my own detrending function or array instead of only being able to use the Savitzky-Golay filter. Perhaps a keyword could be included (user_defined_trend) as an option?

Thanks (and apologies if this is the wrong way to submit a feature request).

**Comment by christinahedges** [comment]
Hi @decaelus, thanks for opening this issue. I'm going to add the label `discussion` here. I believe that this sort of feature might be possible using `Lightkurve`'s `RegressionCorrector` framework. What sort of flattening functions are you hoping to see?

**Comment by decaelus** [comment]
It may not be appropriate to add a user-defined function. It was just a suggestion. Thanks.
