### ISSUE TITLE
Plot light curve with flux without the background subtracted

### ISSUE THREAD

**Issue by gjmluna** [lightkurve/lightkurve#1151]
Hello, I have a target (Target ID 1951435264) which is faint (mag ~ 17) and variable. In the light curve that I downloaded from MAST, the flux is modulated with the expected period with mean flux 0 and negative and positive flux values. I guess that on the bottom part of the light curve the source is below the background while the opposite happens on the top part. Is there a way to not to background subtract the flux?, I'm mostly interested in the period rather than the brightness. 

Thanks

**Comment by gjmluna** [comment]
Hello @barentsen , I'm now able to get back to the analysis of this source but still I don't know how to choose a different background subtraction region, even if now I can run tpf.interact() without problems, can you help me with this?, Thanks!

**Comment by orionlee** [comment]
@gjmluna If you want to choose specific pixels as background, refer to the tutorial:
https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-cutting-out-tpfs.html

While the tutorial is intended for using processing raw data obtained via `search_tesscut()`, the principal would still be applicable if you want to specify custom aperture and custom background with a TPF (as long as you do `tpf_with_bkg = tpf + tpf.flux_bkg` as barentsen suggested).

In the tutorial, it uses `~tpf.create_threshold_mask()` to specify background pixels based on a threshold criteria. If you need further customization, you can modify the result: the mask is just a 2D array of (`Ture`, `False`).
