### ISSUE TITLE
Determining contamination levels from Light Curve Files

### ISSUE THREAD

**Issue by eivshina** [lightkurve/lightkurve#1152]
Hello - 

Would you please let me know if there is a way to assess the contamination level (due to blending with the surrounding stars) of a given light curve downloaded with the search_lightcurve function?

Thanks,
Kate

**Comment by orionlee** [comment]
For lightcurves from TESS produced by the standard SPOC pipeline, contamination assessment information is embedded in the header, accessible via `lc.meta.get('CROWDSAP')` and `lc.meta.get('FLFRCSAP')` in `lightkurve` .

Section 4.1.2 of [The TESS Objects of Interest Catalog from the TESS Prime Mission](https://arxiv.org/abs/2103.12538) paper contains more details on what they mean.

**Comment by christinahedges** [comment]
@eivshina thanks for your comment! I believe @orionlee has answered your question above so I'm going to close this, if you have any more questions please feel free to reach out to tesshelp@bigbang.gsfc.nasa.gov for more specific help on Kepler/TESS light curves!
