### ISSUE TITLE
Search light curve fails

### ISSUE THREAD

**Issue by bmorris3** [lightkurve/lightkurve#1154]
#### Problem description
Search light curve feature fails with "no file found", though it was working yesterday.

#### Example

```python
from lightkurve import search_lightcurve
lcs = search_lightcurve("KIC 10920273", cadence='short', mission='Kepler').download_all(download_dir='data')

# FileNotFoundError: [Errno 2] No such file or directory: 'data/mastDownload/Kepler/kplr010920273_sc_Q113330003330000000/kplr010920273-2009131110544_slc.fits'
```

#### Expected behavior
Should return a light curve collection.

#### Environment

-  platform OS X 10.14
-  lightkurve version: 2.0.9
-  installation method (e.g. pip, conda, source): pip

**Comment by bmorris3** [comment]
This issue seems to have resolved itself.

**Comment by barentsen** [comment]
Oh, interesting!  Should the error return, please add the following at the top:

```python
import lightkurve as lk
lk.log.setLevel("DEBUG")
```

...and let us know what the debug output shows.

Thanks++ for using Lightkurve!
