### ISSUE TITLE
Please restore KeplerPRF to the namespace

### ISSUE THREAD

**Issue by stevepur** [lightkurve/lightkurve#1171]
#### Problem description
Can't import KeplerPRF

#### Example

```python
    from lightkurve import SimpleKeplerPRF
```
fails
#### Expected behavior
that it would be imported.  I fixed it by hand by adding "from .prf import *" to lightkurve/__init__.py and it works fine.

Later this year I will be releasing code that requires KeplerPRF and lightkurve 2.  Early versions of that code is available on Github, and specifies that it requires lightkurve 1.11.  It would be nice to use modern lightkurve in the upcoming more publicly released version.

#### Environment

the latest lightkurve

**Comment by christinahedges** [comment]
Hi @stevepur, thanks for your message! You can still import that class from `Lightkurve` you just need to use
```python
from lightkurve.prf import SimpleKeplerPRF
```
I'm closing this, if you still have an trouble please feel free to comment again!

**Comment by stevepur** [comment]
Thanks, Christina - I've been doing that hoping that API doesn't go awry.  It seems that keplerPRF does not appear on the lightkurve 2 docs.  Are there plans to restore it to the docs?  That would simplify my life when I need to explain what I'm doing.

Also I've got a tess PRF version working and very well tested.  Would you like to do something with that?

**Comment by christinahedges** [comment]
@stevepur heck yes, please open a PR and @Nschanche and I will take a look. We've also been working on a TESSprf class (@Nschanche has been leading this push!) so it will be interesting to see yours and try to merge the two together! If you have any trouble opening a PR let me know (you can use @christinahedges to get my attention). We'll take a look and try to get the best of both worlds.

For the import above that should not change, that is a direct import from the sub module.

For the documentation, this can be something that we'll make sure to add when we have a working TESSprf PR, you're right it needs to be added to the API docs

**Comment by stevepur** [comment]
@Nschanche, @christinahedges, What timescale are you working on for tessPRF?  I don't have bandwidth now to understand the steps of creating a PR but should over the next couple weeks.  On the other hand all I'd be doing is adding a single .py file, so if you want it sooner...
