### ISSUE TITLE
Retire QColumn

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1180]
`QColumn`, and associated `QMaskedColumn`, `QTimeSeries`, can all be retired, given `Astropy.Column` now provides `.value` alias natively.

https://github.com/lightkurve/lightkurve/blob/ad8eb62ae0f6b9d7ecf4183c391fe9891a62a969/src/lightkurve/lightcurve.py#L69

Version: Lightkurve 2.1.1

**Comment by barentsen** [comment]
Yayyy!  🎉 🎉 🎉 🎉 🎉
