### ISSUE TITLE
More informative error reporting upon opening corrupted data products

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1184]
#### Problem description

Right now, when `Lightkurve` opens a FITS file that is corrupted, it produces some cryptic low-level error
(usually suggesting that the file is truncated).

Such cases occur in practice possibly due to download error, e.g., issue #1173 . I recalled it was the root cause of an old issue in using `CBVCorrector` (where it tries to query and download neighboring lightcurves, a lightcurve file is corrupted).

#### Suggestion

Improve error handling (in reading lc / tpf files) so that
1. it explicitly informs users that the file is possibly corrupted.
2. include the actual path of the offending file in the error message

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.1.1

**Comment by orionlee** [comment]
A related error handling issue: After `lightkurve` fails to read a corrupted FITS file and raises some exception, it does not seem to have released the file handle of the corrupted FITS file.

On Windows platform, users cannot delete the corrupted file, until the Python process is stopped (or have the IPython kernel shutdown if the codes are from Jupyter notebooks).

**Comment by orionlee** [comment]
Even after #1228, there are still cases that the error message do not include the data product path.

I encountered the following in downloading & reading a truncated TESS tpf file.

Lightkurve version: main branch, 2.4.0dev

```python
WARNING: File may have been truncated: actual file length (3145728) is smaller than the expected size (43868160) [astropy.io.fits.file]
WARNING:astroquery:File may have been truncated: actual file length (3145728) is smaller than the expected size (43868160)
...
File C:\dev\lightkurve\src\lightkurve\io\read.py:124, in read(path_or_url, **kwargs)
    122 if filetype is not None:
    123     try:
--> 124         return getattr(__import__("lightkurve"), filetype)(path_or_url, **kwargs)
    125     except AttributeError as exc:
    126         raise LightkurveError(
    127             f"Data product f{path_or_url} of type {filetype} is not supported " "in this version of Lightkurve."
    128         ) from exc

File C:\dev\lightkurve\src\lightkurve\targetpixelfile.py:2735, in TessTargetPixelFile.__init__(self, path, quality_bitmask, **kwargs)
   2730 def __init__(self, path, quality_bitmask="default", **kwargs):
   2731     super(TessTargetPixelFile, self).__init__(
   2732         path, quality_bitmask=quality_bitmask, **kwargs
   2733     )
   2734     self.quality_mask = TessQualityFlags.create_quality_mask(
-> 2735         quality_array=self.hdu[1].data["QUALITY"], bitmask=quality_bitmask
   2736     )
   2737     # Early TESS releases had cadences with time=NaN (i.e. missing data)
   2738     # which were not flagged by a QUALITY flag yet; the line below prevents
   2739     # these cadences from being used. They would break most methods!
   2740     if (quality_bitmask != 0) and (quality_bitmask != "none"):
  
...

TypeError: buffer is too small for requested array
```

---

Analysis: The relevant code path:
https://github.com/lightkurve/lightkurve/blob/9763e49b9ae7e794685fed7e0043b5cd67779564/src/lightkurve/io/read.py#L122-L129

It appears that the tpf file in question has enough data to be correctly detected as a TESS tpf file, but the actual reading of it failed because the file is truncated. The exception handling for line 124 does not handle such case, thus the resulting message does not include the file path.

**Comment by wangruibistu** [comment]
I also meet the same warning when downloading the lightcurve files, then can't read the files downloaded truncated. How to fix it?
WARNING: File may have been truncated: actual file length (41744) is smaller than the expected size (178560) [astropy.io.fits.file]
WARNING: File may have been truncated: actual file length (41744) is smaller than the expected size (178560) [astropy.io.fits.file]
WARNING: VerifyWarning: Error validating header for HDU #1 (note: Astropy uses zero-based indexing).
    Header size is not multiple of 2880: 2432
There may be extra bytes after the last HDU or the file is corrupted. [astropy.io.fits.hdu.hdulist]
