### ISSUE TITLE
tpf.interact_sky() for TESS: consider to include stars not in Gaia

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1186]
#### Problem description

For TESS targets, `tpf.interact_sky()` tried to include the TIC / TESS magnitude of the stars when possible (in PR #1050).

Occasionally, the nearby TICs identified by ExoFOP is not in Gaia DR2: [example 1](https://exofop.ipac.caltech.edu/tess/nearbytarget.php?id=18016577), [example 2](https://exofop.ipac.caltech.edu/tess/nearbytarget.php?id=233087860)

Currently, those stars are not plotted. It'd be better if they are also included in the plot.

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.1.1

**Comment by barentsen** [comment]
It makes a lot of sense to me that we should always display these TIC entries.  There may never be a perfect match between TIC<> Gaia, and it is important/useful information to show! Agreed. :+1:
