### ISSUE TITLE
Same condition on lines 176 and 178 in regressioncorrector.py

### ISSUE THREAD

**Issue by Sniperq2** [lightkurve/lightkurve#1192]
What does it should be?

https://github.com/lightkurve/lightkurve/blob/7489f7a6d3eecf7c792ebd85d86c8030c02d9dc6/src/lightkurve/correctors/regressioncorrector.py#L176

https://github.com/lightkurve/lightkurve/blob/7489f7a6d3eecf7c792ebd85d86c8030c02d9dc6/src/lightkurve/correctors/regressioncorrector.py#L178

```
if prior_sigma is not None:
            sigma_w_inv = sigma_w_inv + np.diag(1.0 / prior_sigma ** 2)
if prior_sigma is not None:
            B = B + (prior_mu / prior_sigma ** 2)
```

**Comment by barentsen** [comment]
Oops!  Looks like we can safely remove line 178!
