### ISSUE TITLE
Fix broken TASOC tests

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1200]
#### Problem description

Tests with `--remote-data` enabled are consistently failing (example [CI run](https://github.com/lightkurve/lightkurve/runs/6066111149?check_suite_focus=true)). It seems to be because new [DR5 release](https://archive.stsci.edu/hlsp/tasoc) replaces the DR4 data, breaking some of the tests. Affected tests:

```
FAILED tests/test_units.py::test_tasoc_ppm_units - TypeError: 'NoneType' obje...
FAILED tests/io/test_tasoc.py::test_detect_tasoc - urllib.error.HTTPError: HT...
FAILED tests/io/test_tasoc.py::test_read_tasoc - urllib.error.HTTPError: HTTP...
FAILED tests/io/test_tasoc.py::test_search_tasoc - assert 0 == 1
```

- `test_detect_tasoc() / test_read_tasoc()`: the data product has a new URL:
https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/tasoc/s0001/c1800/0000/0004/1206/4070/hlsp_tasoc_tess_ffi_tic00412064070-s0001-cam3-ccd1-c1800_tess_v05_ens-lc.fits

- `test_search_tasoc()`: the given TIC / sector is still in DR5 release according to their [bulk  download script](https://archive.stsci.edu/hlsps/tasoc/download_scripts/hlsp_tasoc_tess_ffi-tpf_s0001_tess_v05_lc-download.sh). So it might be an interim problem that MAST database has not yet been updated.
- `test_tasoc_ppm_units()`: similar problem (the `HV 2112` referenced is [TIC 183306762](https://exofop.ipac.caltech.edu/tess/target.php?id=183306762), which does exists in the bulk download script)

**Comment by barentsen** [comment]
Issue fixed by merging #1201!  🎉
