### ISSUE TITLE
Search_Tesscut is failing but works from another api

### ISSUE THREAD

**Issue by GGgabbs** [lightkurve/lightkurve#1219]
#### Problem description
We tried to run in the tutorial: https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-cutting-out-tpfs.html
And we get this error message:
SearchError: Unable to download FFI cutout. Desired target coordinates may be too near the edge of the FFI.Error: get_sectors() takes 1 positional argument but 2 were given

It looks like another issue that we found on google: https://github.com/lightkurve/lightkurve/issues/595. This github report suggested that the tesscut service was down, but we confirmed that tesscut is working via @avanderburg custom download script written in a different language on a separate machine.

#### Example
import lightkurve as lk
tpf_result = lk.search_tesscut('HAT-P-11', sector=14)
tpf_result.download()

#### Expected behavior
It should download just like the tutorial

#### Environment
Windows Python Jupyter
Lightkurve 2.0.11 installed via pip or conda

**Comment by Abelink23** [comment]
Hi! Same issue here,

The method for downloading the lightcurves rises that error if you use lk.search_tesscut() method and only works if using lk.search_lightcurve().

**Comment by vbkostov** [comment]
Hi, this might be a platform issue, or a transitory bug at MAST. Can you try again later? I can recreate the tutorial on a MacBook with lightkurve 2.0.11, Jupyter Notebook 6.4.6 and Python 3.7.12.

**Comment by scfleming** [comment]
Might this be a Windows-specific issue?

**Comment by Abelink23** [comment]
I am running macOS Catalina 10.15.7 and running those commands in command line (not jupyter-notebook) and I still get the "TypeError: get_sectors() takes 1 positional argument but 2 were given" error.

**Comment by christinahedges** [comment]
@Abelink23 can you post the Python commands you used, and the full traceback? We'll get this debugged!

**Comment by Abelink23** [comment]
Sure! Here we go:

```
import lightkurve as lk
ID = 'TOI4479.01'
lc = lk.search_tesscut(ID, sector=None) # There are two found output lightcurves so picking one...
lc = lc[0]
lc.download()

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/lightkurve/search.py", line 231, in _download_one
    path = self._fetch_tesscut_path(
  File "/opt/anaconda3/lib/python3.8/site-packages/lightkurve/search.py", line 506, in _fetch_tesscut_path
    sec = TesscutClass().get_sectors(coords)
TypeError: get_sectors() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/lightkurve/utils.py", line 555, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/lightkurve/search.py", line 355, in download
    return self._download_one(
  File "/opt/anaconda3/lib/python3.8/site-packages/lightkurve/search.py", line 248, in _download_one
    raise SearchError(
lightkurve.search.SearchError: Unable to download FFI cutout. Desired target coordinates may be too near the edge of the FFI.Error: get_sectors() takes 1 positional argument but 2 were given

```
I am using:
- Python 3.8.5 
- lightkurve 2.1.0

Thanks a lot! I actually would need this functionality to work as soon as possible 🙏

**Comment by christinahedges** [comment]
Thank you @GGgabbs and @Abelink23, we're all going to have a dig into this and see if we can find the error and the fix. 

This issue raises a potential blind spot in our CI. This is the line from our CI that runs tests on windows

https://github.com/lightkurve/lightkurve/blob/71c4037936578ba0ccd41f387a1def38f1fadb3e/.github/workflows/lightkurve-tests.yml#L90

There's no `remote-data` flag on the tests on windows, so I don't think that tests that pull from MAST will run. @barentsen, do you know if what I'm saying is correct, and if we should add `remote-data` to the tests for windows? Maybe this is not possible?

**Comment by christinahedges** [comment]
It looks like `get_sectors` is part of `astroquery`'s [`TESSCut` class](https://astroquery.readthedocs.io/en/latest/api/astroquery.mast.TesscutClass.html#astroquery.mast.TesscutClass). Can you tell us your version of `astroquery`? You can print it using:

```python
import astroquery
print(astroquery.__version__)
```

**Comment by GGgabbs** [comment]
Hi,

Thank you for your help! This was the solution!! 

I am working in an environment that I just created and had set up some packages in earlier. I did have astroquery 0.4.6 installed on my overall computer, but not in the environment I was running my code in. However, not having astroquery installed did not crash my code as I was only importing lightkurve, which I did have installed. Once I pip installed astroquery into my environment, the tesscut downloaded successfully.

Thank you all again!!

**Comment by christinahedges** [comment]
@GGgabbs that's great! 

For some additional clarity, users can see in the requirement for `lightkurve` in [this](https://github.com/lightkurve/lightkurve/blob/main/pyproject.toml) file. (Depending on how you install, these dependencies should usually automatically be installed when you install lightkurve.)

In that file users will see:
```
astroquery = ">=0.3.10"
```

Which means that `lightkurve` requires an `astroquery` version of 3.10 or higher to work. 

@Abelink23, I suggest you take a look at your `astroquery` install in the environment that you're using `lightkurve` and check you meet this requirement. This should then solve your issue.

**Comment by christinahedges** [comment]
You can also see from the `lightkurve` changelog that there is a similar bug that was addressed in v.2.1.1
```
- Fixed a bug in `search_tesscut(...).download()` which caused TESSCut
downloads to fail when Astroquery v0.4.6 or later is installed. [1176]
```

And so, if possible, updating `lightkurve` to that version or higher would solve this issue.

**Comment by christinahedges** [comment]
@mrtommyb points out that the reason that users have problems with `astroquery` in `lightkurve` is because they deploy a lot of "dev" versions to PyPI as part of their [continuous deployment model](https://astroquery.readthedocs.io/en/latest/). Would changing 
https://github.com/lightkurve/lightkurve/blob/71c4037936578ba0ccd41f387a1def38f1fadb3e/pyproject.toml#L31

to 
```
astroquery = { version = ">=0.3.10*", allow-prereleases = true}
```

Help some users in this case? I wonder if @barentsen or @orionlee have any thoughts?

**Comment by Abelink23** [comment]
> Which means that `lightkurve` requires an `astroquery` version of 3.10 or higher to work.
> @Abelink23, I suggest you take a look at your `astroquery` install in the environment that you're using `lightkurve` and check you meet this requirement. This should then solve your issue.

Hi! Thanks for being checking this! I have **astroquery 0.4.6** installed.

**Comment by Abelink23** [comment]
Hi all, updating lightkurve from 2.1.0 to 2.2.1 indeed solved the issue, thanks!

**Comment by orionlee** [comment]
@GGgabbs @Abelink23 I'm closing the issue, given both of you appear to have the issue resolved. 

The resolution is summarized in discussion post https://github.com/lightkurve/lightkurve/discussions/1224
