### ISSUE TITLE
lightkurve doesn't accept the new GSFC-TESS eleanor light curves

### ISSUE THREAD

**Issue by ethankruse** [lightkurve/lightkurve#1223]
Ok, so trying to use our new HLSP eleanor light curves doesn't work with lightkurve. Here's the example:

```python
import lightkurve as lk
lc_search = lk.search_lightcurve('TIC 150428135')
print(lc_search[:10])
lc_search[7].download()
```

As far as I can tell, you need to add something into `io.detect.detect_filetype` to deal with this.

I was surprised not to already find eleanor in there, so does that mean lightkurve has never been set up to handle eleanor light curves at all? (Perhaps because they've never been available directly from MAST? People always had to use the postcards/TESScut to create their own with the eleanor package?)

I was going to fix and submit a PR myself, but it looks like I'd have to be touching too many things that I don't quite understand, though I'd be happy to give it a shot if you really want me to break everything and then have to come fix my mistakes anyway. :)

**Comment by orionlee** [comment]
@ethankruse There is an active PR working on it: PR #1217  . Your feedback will be welcome!

Specifically, the feedback about the following points would be welcome:
- best way to detect whether a FITS file is from GSFC-TESS-eleanor 
- the FLUX_BKG appears to be in normalized relative in percentage. Is that correct?
