### ISSUE TITLE
Not all light curves from available TESS Sectors found

### ISSUE THREAD

**Issue by reneheller** [lightkurve/lightkurve#1234]
#### Problem description
lightkurve seems to miss light curves from some TESS sectors and I can't find out why and how to resolve this.

#### Example

My test object is 'KIC 7955301' with coordinates '290.18625 +43.72385'.

```python
import lightkurve as lk
search_result = lk.search_lightcurve('290.18625 +43.72385')
print(search_result)
```

gives

```python
#       mission      year   author  exptime  target_name  distance
                                        s                   arcsec 
--- ----------------- ---- --------- ------- ------------- --------
  0 Kepler Quarter 00 2009    Kepler    1800 kplr007955301      0.0
  1 Kepler Quarter 01 2009    Kepler    1800 kplr007955301      0.0
  2 Kepler Quarter 02 2009    Kepler    1800 kplr007955301      0.0
  3 Kepler Quarter 03 2009    Kepler    1800 kplr007955301      0.0
  4 Kepler Quarter 04 2010    Kepler    1800 kplr007955301      0.0
  5 Kepler Quarter 05 2010    Kepler      60 kplr007955301      0.0
  6 Kepler Quarter 05 2010    Kepler    1800 kplr007955301      0.0
  7 Kepler Quarter 06 2010    Kepler    1800 kplr007955301      0.0
  8 Kepler Quarter 07 2010    Kepler    1800 kplr007955301      0.0
  9 Kepler Quarter 08 2011    Kepler    1800 kplr007955301      0.0
 10 Kepler Quarter 09 2011    Kepler    1800 kplr007955301      0.0
 11 Kepler Quarter 10 2011    Kepler    1800 kplr007955301      0.0
 12 Kepler Quarter 11 2012    Kepler    1800 kplr007955301      0.0
 13 Kepler Quarter 12 2012    Kepler    1800 kplr007955301      0.0
 14 Kepler Quarter 13 2012    Kepler    1800 kplr007955301      0.0
 15 Kepler Quarter 14 2012    Kepler    1800 kplr007955301      0.0
 16 Kepler Quarter 15 2013    Kepler    1800 kplr007955301      0.0
 17 Kepler Quarter 16 2013    Kepler    1800 kplr007955301      0.0
 18 Kepler Quarter 17 2013    Kepler    1800 kplr007955301      0.0
 19    TESS Sector 14 2019      SPOC     120     159306035      0.0
 20    TESS Sector 14 2019 TESS-SPOC    1800     159306035      0.0
 21    TESS Sector 14 2019       QLP    1800     159306035      0.0
```

#### Expected behavior
But from the Web TESS Viewing Tool ([WTV](https://heasarc.gsfc.nasa.gov/cgi-bin/tess/webtess/wtv.py)) I know that the object has been observed in Sectors 14 (Cycle 2), 40, 41, and 54 (all Cycle 4).

#### Environment

-  platform (macOS Monterey v12.4), Apple M1 Max
-  lightkurve version 2.2.1
-  installation method: pip

Any help will be appreciated.

René

**Comment by mrtommyb** [comment]
It looks like this source was observed in the FFI data in Sectors 14, 15, 40, and 41. I think you would need to use the tesscut part of lightkurve to get data from this source.

**Comment by reneheller** [comment]
Hi Tom! Thanks, this helped a lot. Now working with the FFI data, I was trying to remove the systematic effects (following [this](https://ssdatalab.github.io/tess-backdrop/lightcurve-example) tutorial) but

```
search_result_tpf_S40 = lk.search_tesscut('290.18625 +43.72385', sector=40).download(cutout_size=(8, 7), quality_bitmask=None)
aper_S40 = search_result_tpf_S40.create_threshold_mask()
r_S40 = tbd.TESSCutCorrector(search_result_tpf_S40, aperture_mask=aper_S40)
```

gives

`ValueError: No solutions exist for Sector 40, Camera 2, CCD 4.`

So I guess if no solution exists I am stuck?

**Comment by orionlee** [comment]
@reneheller I'm not familiar with the particular of `tess-backdrop` package you use. But in general, once you have downloaded a portion of TESS FFI, there are various approaches / packages that could help you to correct systematics, `tess-backdrop` being one of them.

Other options include:
- Do it yourself. Lightkurve has some tutorials on these topics:
https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-cutting-out-tpfs.html
https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-3-how-to-use-cbvcorrector.html

- `eleanor` package.
https://adina.feinste.in/eleanor/

**Comment by reneheller** [comment]
Thanks for those suggestions! These and the tutorial at [https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-cutting-out-tpfs.html](https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-cutting-out-tpfs.html) helped me to solve my little problem. The magic is done by the lk.search_tesscut() function, which extracts light curves from TESS target pixel files. Cheers!

**Comment by orionlee** [comment]
@reneheller Glad to hear your problem is resolved.
