### ISSUE TITLE
Issue while trying to plot lightcurves - "This file may be corrupt due to an interrupted download. Please remove it from your disk and try again."

### ISSUE THREAD

**Issue by aaravys** [lightkurve/lightkurve#1235]
#### Problem description
I am running a code to plot the light curves of 100 eclipsing binaries. After the code is run, some stars are able to be plotted, however, others return this error message: 
```
Not recognized as a supported data product:
C:\Users\aarav\.lightkurve-cache/mastDownload\HLSP\hlsp_gsfc-eleanor-lite_tess_ffi_s0001-0000000126944778_tess_v1.0_lc\hlsp_gsfc-eleanor-lite_tess_ffi_s0001-0000000126944778_tess_v1.0_lc.fits
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.
```

#### Example

```python
import lightkurve as lk
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv('tableDownload-5.csv')

fc = data['id'].tolist()
for i in fc:
    search_result = lk.search_lightcurve(str(i)) #Search LCs directly from TIC
    number_of_authors = np.asarray(search_result,dtype=object).shape[0] #To see how many pipelines there are
    for i in range(number_of_authors):
        try:
            downloaded_file = search_result[i].download() #Download LCs
            flux = downloaded_file.flux #Get flux
            plt.plot(flux)
            plt.show()
            break 
        except Exception as e:
            print(e) #this line prints the error message shown above
```

#### Expected behavior
I expect the code to be able to plot all 100 light curves, but it is unable to plot ~17 lightcurves.
#### Environment

-  platform (e.g. Linux, OSX, Windows): windows
-  lightkurve version (e.g. 1.0b6): v2.2
-  installation method (e.g. pip, conda, source): pip install

Thanks!

**Comment by orionlee** [comment]
The lightcurves from the recently-released [GSFC-ELEANOR-LITE](https://archive.stsci.edu/hlsp/gsfc-eleanor-lite) pipeline is not yet supported by the `lightkurve`. The next release should contain support for it.

**Comment by aaravys** [comment]
@orionlee Thank you for your time! This was very helpful.

**Comment by orionlee** [comment]
@aaravys You're welcome. I'm closing the issue, as I believe it's been addressed.
