### ISSUE TITLE
AssertionError: cbvCorrector expects light curve to be passed in e-/s units.

### ISSUE THREAD

**Issue by supernova-s** [lightkurve/lightkurve#1259]
#### Problem description

How can I deal with this problem below?
When I wanted to create a CBVCorrector object, it jumped out this "AssertionError".

The type of the variable `Earth_like_lc` is `lightkurve.lightcurve.TessLightCurve`.

```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In [40], line 2
      1 from lightkurve.correctors import CBVCorrector
----> 2 cbvCorrector = CBVCorrector(Earth_like_lc)

File ~\anaconda3\envs\tsp\lib\site-packages\lightkurve\correctors\cbvcorrector.py:126, in CBVCorrector.__init__(self, lc, interpolate_cbvs, extrapolate_cbvs, do_not_load_cbvs, cbv_dir)
    123 if not isinstance(lc, LightCurve):
    124     raise Exception('<lc> must be a LightCurve class')
--> 126 assert  lc.flux.unit==Unit('electron / second'), \
    127     'cbvCorrector expects light curve to be passed in e-/s units.'        
    129 if extrapolate_cbvs and (extrapolate_cbvs != interpolate_cbvs):
    130     raise Exception('interpolate_cbvs must be True if extrapolate_cbvs is True')

AssertionError: cbvCorrector expects light curve to be passed in e-/s units.
```

#### Example

```python
from lightkurve.correctors import CBVCorrector
cbvCorrector = CBVCorrector(Earth_like_lc)
```

#### Expected behavior

I wanted to remove the noise using `CBVCorrector` in the lightcurve but I met this problem.
Could you please tell me some solutions?

#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows 11
-  lightkurve version (e.g. 1.0b6):  2.3.0
-  installation method (e.g. pip, conda, source): pip

**Comment by supernova-s** [comment]
Sorry bothering you, I've knew where the problem lies.
It is because I input the flatten lightcurve as parameter that it came up this problem!

**Comment by orionlee** [comment]
It's good to know that you have resolved the issue!

I am closing the issue, because the error message does indicate that it requires a lightcurve in e-/s units.
