### ISSUE TITLE
Creating custom TargetPixelFiles from .fits files?

### ISSUE THREAD

**Issue by void4** [lightkurve/lightkurve#1275]
Is it possible to use lightkurve to create custom TargetPixelFiles from ones own observational data?

Say, if I have a couple hundred calibrated .fits files of the same region in the sky, can I use this library to create TargetPixelFiles and then analyze the lightcurves of one (for confirmation) or many or even all (for discovery) stars in them?

Or is this perhaps not possible but planned or there other tools that can be used to accomplish this?

**Comment by kirxkirx** [comment]
As far as I understand, there is currently no way to create a Target Pixel File from an arbitrary set of FITS images. However, in principle that can be implemented: the example is how lightkurve creates TPFs from TESS FFIs.

Would that be useful? The TPFs make sense in a context of a space photometry mission that tries hard to keep star images on the same detector pixels for the duration of an observing run to minimize systematics. Which pixels are occupied by a target source image is kind of a big deal in this context. The same level of pointing stability is hard to achieve in ground-based observations. Usually, this means that the input images will need to be resampled on a new coordinate grid for the stars on images to maintain same pixel coordinates. This can be done (routinely done of image subtraction), but is it worth it as the new pixels will not be the physical pixels of a detector with their associated systematics?

I would think that a way to go would be to use any other photometry tool to construct a lightcurve. If needed, that lightcurve can be converted to the lightcurve object, so `lighkurve` code for lightcurve manipulation can be applied. (I'm suggesting to skip the TPF creation/lightcurve extraction step.)

A number of general-purpose photometry tools are out there, including [Photutils](https://photutils.readthedocs.io/en/stable/) (Python library), [AstroImageJ ](https://www.astro.louisville.edu/software/astroimagej/) (Java-based cross-platform tool with a nice graphical user interface), [VaST](http://scan.sai.msu.ru/vast/) (disclaimer: that's my code for variable star search) and many-many more...

**Comment by scfleming** [comment]
You can use TESSCut to make cutouts of subsections of all FFIs in a given Sector, and the output are TPF-like objects that we make look as cloas as possible to TPF files.  lightkurve allows to make cutouts from TESS FFIs as a wrapper to TESSCut.

**Comment by scfleming** [comment]
In theory, Astrocut (not lightkurve) is designed to operate on any stack of images, as long as they are formatted in the way it understands.  I'm not sure anyone has tried it out yet with non-TESS images, but it was written to be agnostic in principle.

https://astrocut.readthedocs.io/en/latest/

**Comment by christinahedges** [comment]
Hi @void4 I'm going to close this issue for now, if you want to discuss this functionality more in terms of the `Lightkurve` implementation, please feel free to open a new issue. If you need more help with TESS research, you should also feel free to reach out to the TESS GI helpdesk at tesshelp@bigbang.gsfc.nasa.gov!

**Comment by void4** [comment]
@christinahedges Aye, thank you very much for your response - I haven't gotten around to trying it yet but it's exciting that it's there!
