### ISSUE TITLE
LightkurveError: Not recognized as a supported data product

### ISSUE THREAD

**Issue by diyiliaoya** [lightkurve/lightkurve#1286]
#### Example

```python
import lightkurve as lk 
lcs = lk.search_lightcurve('TIC140898436', exptime=1800,mission='TESS').download_all()
# insert code here ...
```

#### Expected behavior

LightkurveError: Not recognized as a supported data product:
/home/lishijie/.lightkurve/cache/mastDownload/HLSP/hlsp_tglc_tess_ffi_gaiaid-4624742688944261376-s0001-cam4-ccd2_tess_v1_llc/hlsp_tglc_tess_ffi_gaiaid-4624742688944261376-s0001-cam4-ccd2_tess_v1_llc.fits
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.

#### Environment

-  Linux
-  lightkurve 2.4.0
-  pip

**Comment by gully** [comment]
Hi there, it's possible you may have attempted to pre-downloaded this file before and the query is retrieving a corrupted file.  What happens if you remove the file and attempt to re-run the query?

`home/lishijie/.lightkurve/cache/mastDownload/HLSP/hlsp_tglc_tess_ffi_gaiaid-4624742688944261376-s0001-cam4-ccd2_tess_v1_llc/hlsp_tglc_tess_ffi_gaiaid-4624742688944261376-s0001-cam4-ccd2_tess_v1_llc.fits`

**Comment by diyiliaoya** [comment]
> Hi there, it's possible you may have attempted to pre-downloaded this file before and the query is retrieving a corrupted file. What happens if you remove the file and attempt to re-run the query?
> 
> `home/lishijie/.lightkurve/cache/mastDownload/HLSP/hlsp_tglc_tess_ffi_gaiaid-4624742688944261376-s0001-cam4-ccd2_tess_v1_llc/hlsp_tglc_tess_ffi_gaiaid-4624742688944261376-s0001-cam4-ccd2_tess_v1_llc.fits`

It's still the same error after I remove this file.

**Comment by christinahedges** [comment]
Hi @diyiliaoya thanks for getting in touch. I can't reproduce this error unfortunately. I believe this could be to do with the migrating cache from #1214. On importing lightkurve I believe you will get a warning message stating:

```UserWarning: The default Lightkurve cache directory, used by download(), etc., has been moved to [new-dir]. Please move all the files in the legacy directory [legacy-dir] to the new location and remove the legacy directory. Refer to https://docs.lightkurve.org/reference/config.html#default-cache-directory-migration for more information.```

Could you follow the steps at [this](https://docs.lightkurve.org/reference/config.html#default-cache-directory-migration) link to migrate your cache, and see if that fixes the issue?

**Comment by diyiliaoya** [comment]
> Hi @diyiliaoya thanks for getting in touch. I can't reproduce this error unfortunately. I believe this could be to do with the migrating cache from #1214. On importing lightkurve I believe you will get a warning message stating:
> 
> `UserWarning: The default Lightkurve cache directory, used by download(), etc., has been moved to [new-dir]. Please move all the files in the legacy directory [legacy-dir] to the new location and remove the legacy directory. Refer to https://docs.lightkurve.org/reference/config.html#default-cache-directory-migration for more information.`
> 
> Could you follow the steps at [this](https://docs.lightkurve.org/reference/config.html#default-cache-directory-migration) link to migrate your cache, and see if that fixes the issue?

Hi @christinahedges  thanks for your reply. I think it's not relevant the download directory.  I already use the new-dir:
home/lishijie/.lightkurve/cache/mastDownload/HLSP/
I think I found what caused this error. [https://drive.google.com/file/d/1z7GYQzzQ-_yiDFI92l7ug9M9a1yl_KYf/view?usp=share_link](url)
The upper picture lists the search results of TIC140898436. The row 4 which of author named "TGLC" is the reason. 
I specified the parameter "author" when I used search_lightkure().download_all()
The value of "author" should be anyone except for "TGLC".

**Comment by christinahedges** [comment]
@diyiliaoya thanks for raising this! I now understand, TGLC is a new High Level Science Product at MAST that -just- came out. `Lightkurve` doesn't have a way to read this new HLSP and so I'll do some digging to figure out why this is getting returned in the search result and what we can do to address it. 

I'll work on this, for now I would narrow your search to ignore authors that are TGLC. 

I'll report back!

**Comment by christinahedges** [comment]
@diyiliaoya I just opened a PR #1291 which will address this and enable TGLC light curves to be read in.

**Comment by diyiliaoya** [comment]
> @diyiliaoya I just opened a PR #1291 which will address this and enable TGLC light curves to be read in.

Thanks!

**Comment by christinahedges** [comment]
@diyiliaoya I just merged in a fix for this issue which adds a new reader for that HLSP. If you'd like to make sure your `Lightkurve` version can now read those files, you can update to the `main` branch version available on GitHub. If it's not urgent, you can wait a week or two and I will release version 2.4.1 of `Lightkurve` to pypi.

**Comment by diyiliaoya** [comment]
> @diyiliaoya I just merged in a fix for this issue which adds a new reader for that HLSP. If you'd like to make sure your `Lightkurve` version can now read those files, you can update to the `main` branch version available on GitHub. If it's not urgent, you can wait a week or two and I will release version 2.4.1 of `Lightkurve` to pypi.

Thank you ! I will wait for the new version.
