### ISSUE TITLE
SearchResult containing 0 data products 

### ISSUE THREAD

**Issue by JosephKarpinski** [lightkurve/lightkurve#1346]
#### Problem description
So many print statements of search-result: search_result =lk.search_lightcurve(“TIC xxxxxxxx”) 
return SearchResult containing 0 data products 
Why? Is this a problem with LightKurve, Simbad, or TESS?

See attached working and non-working examples.
<img width="981" alt="Screenshot 2023-06-27 at 12 01 33 PM" src="https://github.com/lightkurve/lightkurve/assets/37123616/1b9deced-7d1c-46ba-9ca8-6ad13c96e181">
<img width="981" alt="Screenshot 2023-06-27 at 12 01 48 PM" src="https://github.com/lightkurve/lightkurve/assets/37123616/bff07e6b-5ae7-418d-9bb3-f3cae7ff8399">

#### Example

import lightkurve as lk

search_result =lk.search_lightcurve(“TIC 35401949”)
print(search_result)

#### Environment

-  platform (OSX)
-  lightkurve version (2.4.0)
-  installation method (pip)

**Comment by rebekah9969** [comment]
Dear @JosephKarpinski

Thank your for posting your this issue. It looks like the targets that are returning zero search results were not targeted objects observed by TESS. This means that there are no light curve files or target pixel files created for these objects. Using the code below however you can search the TESS FFIs and find your object of interest there.

`search_result = lk.search_tesscut("TIC 1996955834")`

You can learn more about the different kinds of TESS products on our [data products page](https://heasarc.gsfc.nasa.gov/docs/tess/data-products.html).

A tutorial demonstrating what to do in such cases is provided [here](https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-cutting-out-tpfs.html)

I hope that this helps.

**Comment by Nschanche** [comment]
Hi @JosephKarpinski, I followed the referenced tutorial for the TIC provided and was able to successfully make a lightcurve. I will note that there was a big spike in flux at around BTJD 2804 that makes the lightcurve look bad. However, I checked the [data release notes](https://archive.stsci.edu/missions/tess/doc/tess_drn/tess_sector_55_drn79_v02.pdf) for sector 55 (the sector in which this target was observed), and it notes that the moon passes through camera 1 during the first orbit. As this target is was observed with camera 1 and the spike corresponds with the noted time of the moon passing, this spike in flux can be attributed to the moon. Masking out the affected time range will produce a nice lightcurve. If you are encountering other problems or errors, please provide the traceback information and we can look into it further.

**Comment by christinahedges** [comment]
@JosephKarpinski I'm going to close this, if you still require help please let us know, or email us at [tesshelp@bigbang.gsfc.nasa.gov](tesshelp@bigbang.gsfc.nasa.gov).
