### ISSUE TITLE
Add implicit JupyterHub support

### ISSUE THREAD

**Issue by jaytmiller** [lightkurve/lightkurve#1348]
#### Problem description
As-is,  lightkurve does not operate well from a JupyterHub session of JupyterLab due to the way Bokeh handles server ports and JupyterHub's proxy.  

The cure is documented here: https://docs.bokeh.org/en/latest/docs/user_guide/output/jupyter.html

Because it's easy to find solutions which don't work,  and its a pain to modify notebooks created locally for JupyterHub,  we propose some lightkurve tweaks which make the use of the fix above implicit,  automatically selected when JupyterHub defines the environment variable **LK_JUPYTERHUB_EXTERNAL_URL** which has a hub specific value of e.g. **https://timeseries.science.stsci.edu**.   With that variable set,  the tweaks automatically define Bokeh's workaround as a replacement for the notebook_url parameter making lightkurve notebooks work on JupyterHub with no changes.
#### Example

Without the proposed tweaks the code below fails.   With the tweaks the unmodified code works.

```python
import lightkurve as lk
tpf = lk.search_targetpixelfile("HL Tau", author='K2', campaign=13, cadence='long').download()
tpf.interact()
```

#### Expected behavior

Without the tweaks the snippet fails to show the interact widgets.

#### Environment

-  platform (e.g. Linux / JupyterHub):
-  lightkurve version (2.4.0):
-  installation method (e.g. pip, source):

**Comment by christinahedges** [comment]
This was merged in the new version, thanks for opening the PR and adding this functionality!
