### ISSUE TITLE
New feature request with pull request coming: lc.remove_data(start=start,end=end,col='str')

### ISSUE THREAD

**Issue by astromattwood** [lightkurve/lightkurve#1353]
#### Problem description
For my work it is useful to remove small sections of data.  E.g., just before the mid-sector gap the star is in eclipse ingress, but hasn't reached eclipse midpoint.  In this case it is better to simply remove those ingress points.  

So I'm wanting functionality that is similar to the 'truncate' method, but able to remove data points by time within a light curve object.

I've followed the developer instructions and have tested the code below (inserted just after 'truncate'), and it appears to work.  Of course the core developers may want to change the name, argument names, etc.

I did think it should be required that both 'start' and 'end' be passed, and I think this does that.

#### Example
    def remove_data(self, start: float = None, end: float = None, column: str = "time"):
        """remove eata from the light curve between two values.

        Parameters
        ----------
        start : float
            Clip all rows between start and end
        end: float
            Clip all rows between start and end
        column : str, optional
            The name of the column on which the clipping is based. Defaults to 'time'.

        Returns
        -------
        clipped_lc : LightCurve
            The clipped light curve.
        """
        def _to_unitless(data):
            return np.asarray(getattr(data, "value", data))

        mask = np.ones(len(self), dtype=bool)

        if end and start:
            mask &= (_to_unitless(getattr(self, column)) >= end) | (_to_unitless(getattr(self, column)) <= start)
        return self[mask]

#### Expected behavior

N/A
#### Environment
MacOS 
LK 2.4.0

-  platform (e.g. Linux, OSX, Windows):
-  lightkurve version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):

**Comment by rebekah9969** [comment]
Dear @astromattwood,

Thank you very much for posting this issue.
While your code is indeed useful, there are already ways to create boolean masks to block out specific time series data using python and lightkurve e.g.,

`lc_n = lc[(lc.time.value < start) | (lc.time.value > end)]`

There are also specific ways to mask out data which might contain transits or other phenomena as shown here (https://docs.lightkurve.org/tutorials/3-science-examples/exoplanets-identifying-transiting-planet-signals.html)
As such adding in this function, while useful, would be an unnecessary step and might not represent all functionality that a user may desire.

We however sincerely think you for your interest and will keep this in mind if we ever do move in this direction.

We will close this issue now, but please feel free to post again to open it back up.

**Comment by astromattwood** [comment]
Dear Rebekah (et al.)

Well, derp - I don’t know why I didn’t think of that, since that’s essentially what .truncate() is doing as well, and I used that kind of masking all the time!  I should have just asked your team instead of plowing ahead, but  it was an interesting few hours figuring out how to modify the code and all, so not completely time wasted in my book.

Thanks again for all the effort that’s gone into lightkurve - much appreciated from a community user.

Cheers,
Matt

--
Matt A. Wood, Ph.D.
Regents Professor of Physics & Astronomy 
Texas A&M University-Commerce
Commerce, TX 75429
O: 903.886.5486     M: 903.269.6682
