### ISSUE TITLE
Issue with lk.search_lightcurve(TIC, author = 'SPOC') with AttributeError: module 'lightkurve' has no attribute 'search_lightcurve'

### ISSUE THREAD

**Issue by rebekah9969** [lightkurve/lightkurve#1356]
When I type this command:
sector_data = lk.search_lightcurve(TIC, author = 'SPOC')

this is showing:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 sector_data = lk.search_lightcurve(TIC, author = 'SPOC')

AttributeError: module 'lightkurve' has no attribute 'search_lightcurve'

_Originally posted by @Hiyabiswas in https://github.com/lightkurve/lightkurve/issues/1355#issuecomment-1669472577_

**Comment by rebekah9969** [comment]
@Hiyabiswas 

When running this code for TIC 236887394

`sector_data = lk.search_lightcurve("TIC 236887394", author = 'SPOC')`

There are 11 data products. Could you please tell me the environment set up.

**Environment**
platform (e.g. Linux, OSX, Windows): 
lightkurve version (e.g. 1.0b6): 
installation method (e.g. pip, conda, source): 

Could you also please post the full code you are using where this error occurs? 

Thank you.

**Comment by Hiyabiswas** [comment]
Mam, I have given these command:
import lightkurve as lk
import matplotlib.pyplot as plt
TIC = 'TIC 236887394'
sector_data = lk.search_lightcurve(TIC, author = 'SPOC')
and found this result:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 sector_data = lk.search_lightcurve(TIC, author = 'SPOC')

AttributeError: module 'lightkurve' has no attribute 'search_lightcurve'


Environment set up:
Platform: Linux (Fedora)
Lightkurve version:   python -c "import lightkurve; print(lightkurve.__version__)"
2.4.0

Installation method: python -m pip install lightkurve --upgrade

**Comment by bahar1991v** [comment]
Hello
I work with the Lightkurve package and it gives me this error(KeyError: 'dataURL')in the download section of the star sectors. 
Thank you for guiding me.
![Screenshot (1)](https://github.com/lightkurve/lightkurve/assets/107683666/ad5e4aac-4eb2-4b14-abca-f3853f8ce932)

**Comment by keyuxing** [comment]
> Hello I work with the Lightkurve package and it gives me this error(KeyError: 'dataURL')in the download section of the star sectors. Thank you for guiding me. ![Screenshot (1)](https://user-images.githubusercontent.com/107683666/279655903-ad5e4aac-4eb2-4b14-abca-f3853f8ce932.png)

See #1377

**Comment by Nschanche** [comment]
Closing this issue as it seems to be a local environment issue, but you can reopen if you have further troubles importing lightkurve.
