### ISSUE TITLE
issue with tutorial line returning The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by cheesyminecart** [lightkurve/lightkurve#1357]
just got this package, the tutorial was rather straightforward until i got to the third line: 

```py
lc = pixelfile.to_lightcurve(aperture_mask="all");
```

This just returns: 

```py
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
the other error messages i get include: 

`
--> if aperture_mask is None or aperture_mask == "all":
aperture_mask = np.ones((self.shape[1], self.shape[2]), dtype=bool)
elif aperture_mask == "pipeline":
`

`
--> flux, flux_err, centroid_col, centroid_row = self._aperture_photometry(
`

`
if method in ["aperture", "sap"]:
--> return self.extract_aperture_photometry(**kwargs)
`
The rest of my code: 
```py
from lightkurve import search_targetpixelfile

pixelfile = search_targetpixelfile("KIC 8462852", cadence="long", quarter=16).download();
pixelfile.plot(frame=1);
lc.plot();
```
Where declaring lc is before the lc.plot() line

**Comment by davidedionese** [comment]
I have the same issue. I get the same error when trying to apply any custom mask (only specifying 'pipeline' works for me).
The error appears when just plotting too (targetpixelfile.plot(aperture_mask=...)).
Using version 2.4. Python 3.10. On a Ubuntu machine.

**Comment by rebekah9969** [comment]
@cheesyminecart 

Thank you very much for posting this issue. 
Could you please provide me with a little more information regarding the environment you are using lightkurve in.

**Environment**
platform (e.g. Linux, OSX, Windows):
lightkurve version (e.g. 1.0b6):
installation method (e.g. pip, conda, source):

**Comment by rebekah9969** [comment]
@davidedionese 

Thank you very much for posting your issue. Could you please send me an example of the code and the problem that you are finding. Thank you.

**Comment by davidedionese** [comment]
Yes indeed.
My code (I am basically following the [tutorial for the SNR](https://docs.lightkurve.org/tutorials/3-science-examples/periodograms-optimizing-the-snr.html) of the periodogram):
```ruby
import lightkurve as lk
import matplotlib.pyplot as plt
import numpy as np
import astropy.units as u

TARGET = "EPIC 211416749"
tpf = lk.search_targetpixelfile(TARGET, author="K2", campaign=5, cadence='short').download()

target_mask = tpf.create_threshold_mask(threshold = 10, reference_pixel = 'center')
tpf.plot(scale='log', aperture_mask=target_mask)
```

After the last line I get the following error:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

The line:
```ruby
tpf.plot(scale='log', aperture_mask=tpf.pipeline_mask)
```
as suggested in the tutorial throws the same error.

Then I also try:
```ruby
lc = tpf.to_lightcurve()
```
and I get the exact same error.
I am working in a conda environment, installing all packages through conda.
lightkurve version 2.4.0
Linux machine.

**Comment by davidedionese** [comment]
- Python version: 3.11.4
- Numpy version: 1.25.2 (maybe it matters)
- matplotlib version: 3.7.1
Only these packages (and dependencies) are installed in the environment. 
Conda version: 23.7.2.
The custom mask looks like this:
```
array([[False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False, False, False, False, False],
       [False, False, False, False,  True,  True,  True, False, False, False, False],
       [False, False, False, False,  True,  True,  True,  True, False, False, False],
       [False, False, False, False,  True,  True,  True,  True, False, False, False],
       [False, False, False, False,  True,  True,  True,  True,  True, False, False],
       [False, False, False, False, False,  True,  True,  True, False, False, False],
       [False, False, False, False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False]])
```

**Comment by cheesyminecart** [comment]
Dear Rebekah, 
Thanks for the reply! Sorry I wasn't able to give my own contribution to the discussion, though I am willing to provide the necessary details for a quick bugfix. 

platform: OSX
installation: pip3
lk version: 2.4.0

**Comment by rebekah9969** [comment]
Dear @cheesyminecart & @davidedionese 

After much investigation by myself and my colleagues we have determined that this issue is related to the most recent version of numpy - version 1.25.0.

Within this version there was deprecation expiration and now an array of all True or all False is returned when values are fundamentally not comparable (e.g. have different dtypes). An example is:

`np.array(["a"]) ==np.array([1])."`

You can read more about this [here](https://numpy.org/doc/stable/release/1.25.0-notes.html).

We are working on a fix for this issue,  but in the meantime it might be worthwhile installing an older version of numpy. 

Thank you once again for posting this issue and please let us know there are any more issues.

**Comment by davidedionese** [comment]
Dear @rebekah9969, 

I tried with an older version of Numpy and indeed it works fine.

Thank you very much to you and your colleagues for your patience and your time!

**Comment by christinahedges** [comment]
@davidedionese, @cheesyminecart, please try updating to the newest version of `lightkurve` which is 2.4.1, and report back here if this does not solve your issue!
