### ISSUE TITLE
Light curve does not search multiple cadences correctly

### ISSUE THREAD

**Issue by GijsMulders** [lightkurve/lightkurve#1359]
#### Problem description
LightKurve does not return all the specified cadences

#### Example
```python
import lightkurve as lk
search_result = lk.search_lightcurve('TIC 296739893', mission='TESS', exptime=[120,600,1800])
```
Returns a list of all data products but without the 1800s cadences included

<img width="450" alt="Result" src="https://github.com/lightkurve/lightkurve/assets/13457058/6a0f7554-c016-445c-8d85-8da3f975081d">

#### Expected behavior
```python
import lightkurve as lk
search_result = lk.search_lightcurve('TIC 296739893', mission='TESS')
```
Without the exptime keyword it does return the 1800s cadence.

<img width="508" alt="Expected" src="https://github.com/lightkurve/lightkurve/assets/13457058/33c017f8-1891-4ea5-b5fc-90ead8193a99">

#### Environment

-  platform: OSX
-  lightkurve version: 2.0.11
-  installation method: pip

**Comment by rebekah9969** [comment]
Hello @GijsMulders 

Thank you for posting this issue. 
I believe that the code

`search_result = lk.search_lightcurve('TIC 296739893', mission='TESS', exptime=[120,1800])`

would return your desired result since this is specifying a range of exposure times.

**Comment by GijsMulders** [comment]
Ah, that yes that works!

I assumed exptime was a list not a range...
