### ISSUE TITLE
Error calling .to_periodogram

### ISSUE THREAD

**Issue by karsten-brogaard** [lightkurve/lightkurve#1362]
#### Problem description

I get an error when trying to create a periodogram with ".to_periodogram". See example below

#### Example
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightkurve as lk
>>> sr=lk.search_lightcurve('211976270')
>>> lc=sr[11].download()
>>> pg=lc.normalize().to_periodogram()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kfb/.local/lib/python3.10/site-packages/lightkurve/lightcurve.py", line 2363, in to_periodogram
    return LombScarglePeriodogram.from_lightcurve(lc=self, **kwargs)
  File "/home/kfb/.local/lib/python3.10/site-packages/lightkurve/periodogram.py", line 918, in from_lightcurve
    if not implementations.main._is_regular(frequency) and ls_method in [
AttributeError: module 'astropy.timeseries.periodograms.lombscargle_multiband.implementations.main' has no attribute '_is_regular'

#### Environment

Ubuntu 
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Lightkurve 2.4.0 installed with pip

**Comment by SergeParis68** [comment]
Hello, I have exactely the same issue on Windows.
So not related to the OS.

**Comment by keyuxing** [comment]
See https://github.com/lightkurve/lightkurve/issues/1347#issuecomment-1621071068

And I think we should release lightkurve v2.4.1 ASAP

**Comment by SergeParis68** [comment]
Hello keyuxing, thanks for the comment. Not sure I understood it well. Are you part of the development team ? Does that mean that this bug is fixed in the the next 2.4.1. version ? Any idea when it could be made availablle ?
Thanks again.

**Comment by Nschanche** [comment]
Hi @SergeParis68, the fix is currently part of 2.4.1dev, but a minor release containing the fix will be appearing soon.

**Comment by SergeParis68** [comment]
Thanks a lot.

Can I shoot two additional newbie questions ?
- Is it possible to install a DEV version or should I wait for the minor official version ?
- how should I know this minor version is indeed released ?
Thanks again !

**Comment by keyuxing** [comment]
> Thanks a lot.
> 
> Can I shoot two additional newbie questions ?
> 
> * Is it possible to install a DEV version or should I wait for the minor official version ?
> * how should I know this minor version is indeed released ?
>   Thanks again !

The temporary workaround is in https://github.com/lightkurve/lightkurve/issues/1347#issuecomment-1621071068

**Comment by SergeParis68** [comment]
thanks a lot for all of your help
Serge/

**Comment by christinahedges** [comment]
@karsten-brogaard, @SergeParis68, please try updating to the newest version of `lightkurve` which is 2.4.1, and report back here if this does not solve your issue!

**Comment by SergeParis68** [comment]
> @karsten-brogaard, @SergeParis68, please try updating to the newest version of `lightkurve` which is 2.4.1, and report back here if this does not solve your issue!

Hello.

I do confirm : it works.

I did the follwing tests : 
   - with 2.4.0 : I ran 2 different codes : 2 FAILURES (see attached files _Code 1 LightKurve 2 4 0_ & _Code 2 LightKurve 2 4 0_)
   - installed 2.4.1 : fully closed Anaconda, restarted and ran the 2 codes : 2 SUCCESSES (see attached files _Code 1 LightKurve 2 4 1_ & _Code 2 LightKurve 2 4 1_)
   - reversed back to 2.4.0 : fully closed Anaconda, restarted and ran the 2 codes : 2 FAILURES
   - re-installed 2.4.1 : fully closed Anaconda, restarted and ran the 2 codes : 2 SUCCESSES

Thanks again for the release !

Serge/



![Code 1 _ LightKurve 2 4 0](https://github.com/lightkurve/lightkurve/assets/144069167/8eb2b2a6-15af-4576-b5e0-5c57c3f0f1b1)
![Code 1 _ LightKurve 2 4 1](https://github.com/lightkurve/lightkurve/assets/144069167/653af15c-d209-4874-a788-5345075733ae)
![Code 2 _ LightKurve 2 4 0](https://github.com/lightkurve/lightkurve/assets/144069167/c424fe95-08ab-4e16-90f9-a161aace3674)
![Code 2 _ LightKurve 2 4 1](https://github.com/lightkurve/lightkurve/assets/144069167/d6e7e10a-3858-4d58-9b42-268d1fd2b327)
