### ISSUE TITLE
Typo in "Searching & downloading Kepler, K2, and TESS data" tutorial

### ISSUE THREAD

**Issue by stephsa2023** [lightkurve/lightkurve#1368]
"search_lightcurve returns a SearchResult table, which contains information about the data products available to download. This search result tells us that KIC 3733346 was observed in Kepler Quarters 1–16."
Shouldn't this be 1-17?

**Comment by Nschanche** [comment]
Hello, is it possible your table display was truncated? I searched for that target and see sectors 1-17. 
<img width="554" alt="Screenshot 2023-10-18 at 4 45 15 PM" src="https://github.com/lightkurve/lightkurve/assets/8659773/8c28f6ec-aa3e-4b48-b45c-60ace34793d6">

**Comment by keyuxing** [comment]
> Hello, is it possible your table display was truncated? I searched for that target and see quarters 1-17. <img alt="Screenshot 2023-10-18 at 4 45 15 PM" width="554" src="https://user-images.githubusercontent.com/8659773/276396385-8c28f6ec-aa3e-4b48-b45c-60ace34793d6.png">

He might refer to the text in "docs/source/tutorials/1-getting-started/searching-for-data-products.ipynb"

<img width="542" alt="image" src="https://github.com/lightkurve/lightkurve/assets/67900886/487e6882-d269-4065-a5fb-131cc3e5de08">

**Comment by Nschanche** [comment]
Oh, I see that in the tutorial, yes you are right. This will be updated to say 1-17. Thank you!

**Comment by Nschanche** [comment]
I have made PR #1370  to correct the wording in the tutorial. I'll close this issue now, but please reach out again if you encounter other issues.
