### ISSUE TITLE
Type error on stitch()

### ISSUE THREAD

**Issue by cmorsoc** [lightkurve/lightkurve#1373]
#### Problem description
An script to download lightkurves, which worked two years ago, doesn't work with current version of lightkurve.
The line fails:
lc_set = lk.search_lightcurve(star,author=catalog,cadence='long').download_all().stitch()

Error message:
TypeError                                 Traceback (most recent call last)
Cell In[13], line 65
     64 # ...
---> 65 lc_set = lk.search_lightcurve(star,author=catalog,cadence='long').download_all().stitch()

File ~/anaconda3/lib/python3.11/site-packages/lightkurve/collections.py:197, in LightCurveCollection.stitch(self, corrector_func)
    195 with warnings.catch_warnings():  # ignore "already normalized" message
    196     warnings.filterwarnings("ignore", message=".*already.*")
--> 197     lcs = [corrector_func(lc) for lc in self]
    199 # Address issue #954: ignore incompatible columns with the same name
    200 columns_to_remove = set()

File ~/anaconda3/lib/python3.11/site-packages/lightkurve/collections.py:197, in <listcomp>(.0)
    195 with warnings.catch_warnings():  # ignore "already normalized" message
    196     warnings.filterwarnings("ignore", message=".*already.*")
--> 197     lcs = [corrector_func(lc) for lc in self]
    199 # Address issue #954: ignore incompatible columns with the same name
    200 columns_to_remove = set()
...

#### Expected behavior
We should get the lightkurve data

#### Environment

Zorin Linux Pro 16.2 (Ubuntu)
lightkurve 2.4.1

**Comment by orionlee** [comment]
Please provide the specific example so that the problem can be reproduced. What is the `star` and `catalog` in the example?

```
lc_set = lk.search_lightcurve(star,author=catalog,cadence='long').download_all().stitch()
```

**Comment by cmorsoc** [comment]
Hi @orionlee, I'm sorry, it must be an issue with the local Python installation because It runs perfectly on Google Colab.
Thanks,
Carlos

**Comment by orionlee** [comment]
I'm closing the issue as it sound like to be an issue of corrupted environment. @cmorsoc , write back if you believe otherwise.
