### ISSUE TITLE
Attempts to download from lightkurve results in a KeyError: 'dataURL'

### ISSUE THREAD

**Issue by ThisIsTheIC** [lightkurve/lightkurve#1377]
#### Problem description
Hello.

When I try to download a target pixel file or a lightcurve from lightkurve, the download will not complete because of a KeyError. I am able to use cached files just fine. I used the same kind of code yesterday (October 30, 2023) and it worked just fine. There have been no updates to any packages that I am aware of in the interim--indeed, the first time I encountered this error I was in a virtual environment with an older version of lightkurve (and a few other packages).

#### Example

```python
import lightkurve as lk
lc3 = lk.search_lightcurve("TIC 179119903", sector=66).download()
```

#### Expected behavior
The download should complete.

If you would like the trace, it is here:
```python
lc3 = lk.search_lightcurve("TIC 179119903", sector=66).download()

~/anaconda3/lib/python3.8/site-packages/lightkurve/utils.py in wrapper(*args, **kwargs)
    561             sys.stdout = devnull
    562             try:
--> 563                 return f(*args, **kwargs)
    564             # restore to default
    565             finally:

~/anaconda3/lib/python3.8/site-packages/lightkurve/search.py in download(self, quality_bitmask, download_dir, cutout_size, **kwargs)
    421             )
    422 
--> 423         return self._download_one(
    424             table=self.table[:1],
    425             quality_bitmask=quality_bitmask,

~/anaconda3/lib/python3.8/site-packages/lightkurve/search.py in _download_one(self, table, quality_bitmask, download_dir, cutout_size, **kwargs)
    340             else:
    341                 from astroquery.mast import Observations
--> 342                 download_url = table[:1]["dataURL"][0]
    343                 log.debug("Started downloading {}.".format(download_url))
    344                 download_response = Observations.download_products(

~/anaconda3/lib/python3.8/site-packages/astropy/table/table.py in __getitem__(self, item)
   2073     def __getitem__(self, item):
   2074         if isinstance(item, str):
-> 2075             return self.columns[item]
   2076         elif isinstance(item, (int, np.integer)):
   2077             return self.Row(self, item)

~/anaconda3/lib/python3.8/site-packages/astropy/table/table.py in __getitem__(self, item)
    261         """
    262         if isinstance(item, str):
--> 263             return OrderedDict.__getitem__(self, item)
    264         elif isinstance(item, (int, np.integer)):
    265             return list(self.values())[item]

KeyError: 'dataURL'
```

I've played around a bit with the cache config to see if that had anything to do with it. It did not seem to.

#### Environment

-  platform (e.g. Linux, OSX, Windows): Linux (Ubuntu 20.04) and OSX
-  lightkurve version (e.g. 1.0b6): 2.4.0 (Ubuntu only) and 2.0.9 (both)
-  installation method (e.g. pip, conda, source): pip

**Comment by warrickball** [comment]
I happen to have just run into something similar:
```pycon
>>> import lightkurve as lk
>>> q = lk.search_lightcurve('HD 53929', mission='TESS')
>>> lc = q[0].download()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[4], line 1
----> 1 lc = q[0].download()

File ~/.local/lib/python3.11/site-packages/lightkurve/utils.py:566, in suppress_stdout.<locals>.wrapper(*args, **kwargs)
    564 sys.stdout = devnull
    565 try:
--> 566     return f(*args, **kwargs)
    567 # restore to default
    568 finally:
    569     sys.stdout = old_out

File ~/.local/lib/python3.11/site-packages/lightkurve/search.py:432, in SearchResult.download(self, quality_bitmask, download_dir, cutout_size, **kwargs)
    422 if len(self.table) != 1:
    423     warnings.warn(
    424         "Warning: {} files available to download. "
    425         "Only the first file has been downloaded. "
   (...)
    429         LightkurveWarning,
    430     )
--> 432 return self._download_one(
    433     table=self.table[:1],
    434     quality_bitmask=quality_bitmask,
    435     download_dir=download_dir,
    436     cutout_size=cutout_size,
    437     **kwargs,
    438 )

File ~/.local/lib/python3.11/site-packages/lightkurve/search.py:351, in SearchResult._download_one(self, table, quality_bitmask, download_dir, cutout_size, **kwargs)
    348 else:
    349     from astroquery.mast import Observations
--> 351     download_url = table[:1]["dataURL"][0]
    352     log.debug("Started downloading {}.".format(download_url))
    353     download_response = Observations.download_products(
    354         table[:1], mrp_only=False, download_dir=download_dir
    355     )[0]

File ~/.local/lib/python3.11/site-packages/astropy/table/table.py:2055, in Table.__getitem__(self, item)
   2053 def __getitem__(self, item):
   2054     if isinstance(item, str):
-> 2055         return self.columns[item]
   2056     elif isinstance(item, (int, np.integer)):
   2057         return self.Row(self, item)

File ~/.local/lib/python3.11/site-packages/astropy/table/table.py:264, in TableColumns.__getitem__(self, item)
    253 """Get items from a TableColumns object.
    254 
    255 ::
   (...)
    261   tc[1:3] # <TableColumns names=('b', 'c')>
    262 """
    263 if isinstance(item, str):
--> 264     return OrderedDict.__getitem__(self, item)
    265 elif isinstance(item, (int, np.integer)):
    266     return list(self.values())[item]

KeyError: 'dataURL'
```
I just tried λ Nor and V1175 Cas, both of which failed, so I wonder if there's an upstream issue, perhaps with MAST itself. I haven't much more time to look at this today.

**Environment**
* platform (e.g. Linux, OSX, Windows): Linux (Fedora 38)
* lightkurve version (e.g. 1.0b6): 2.4.1
* installation method (e.g. pip, conda, source): pip

**Comment by warrickball** [comment]
Perhaps the desired field has changed its name to `'dataURI'`?
```pycon
>>> print('\n'.join(q[0].table.colnames))
intentType
obs_collection
provenance_name
instrument_name
project
filters
wavelength_region
target_name
target_classification
sequence_number
obs_id
s_ra
s_dec
proposal_id
proposal_pi
dataproduct_type
calib_level
t_min
t_max
t_exptime
em_min
em_max
obs_title
t_obs_release
proposal_type
dataRights
mtFlag
obsid
objID
objID1
distance
exptime
obsID
obs_collection_products
dataproduct_type_products
description
type
dataURI
productType
productGroupDescription
productSubGroupDescription
productDocumentationURL
project_products
prvversion
proposal_id_products
productFilename
size
parent_obsid
dataRights_products
calib_level_products
author
mission
#
year
sort_order
>>> print(q[0].table['dataURI'])
                                             dataURI                                              
--------------------------------------------------------------------------------------------------
mast:HLSP/qlp/s0033/0000/0002/9228/8128/hlsp_qlp_tess_ffi_s0033-0000000292288128_tess_v01_llc.fits

```

**Comment by davidjwilson** [comment]
Hi all,

Just add another data point, I had the same problem, and Warrick's solution also worked for me.

**Environment**

- platform (e.g. Linux, OSX, Windows): Linux (Mint 21)
- lightkurve version (e.g. 1.0b6): 2.4.1
- installation method (e.g. pip, conda, source): pip

**Comment by orionlee** [comment]
Somehow MAST no longer returns `dataURL` column (it used to return `dataURI` and `dataURL`). `lightkurve` has been using `dataURL` to download the products.

@scfleming Has MAST dropped `dataURL` column?

---
**Workaround**: Similar to what Warrick suggested, one can also do it without changing `lightkurve` source code by creating the `dataURL` column in the search result in application codes:

```python
sr = lk.search_lightcurve("TIC278525028")
sr.table["dataURL"] = sr.table["dataURI"]  # workaround MAST issue
lcc = sr.download_all()
```

**Comment by scfleming** [comment]
Thanks for letting me know, I will inquire with the team. In the mean time, if using `dataURI` can serve as a temporary work-around I'd recommend doing that until further notice.

**Comment by warrickball** [comment]
FWIW, it looks like Lightkurve already uses `'dataURI'` for Kepler products:
https://github.com/lightkurve/lightkurve/blob/4f2dbedb2d61e24348b43f36cfd3259f06d6d297/src/lightkurve/search.py#L1350

**Comment by scfleming** [comment]
So far we haven't noticed anything that would explain this change. Yesterday was a monthly patch for us, but none of the changes we made should have changed this detail. I'm going to keep checking in with folks here, there's a possibility the recommendation would be to change so everything uses `dataURI` for returned products, but I don't yet understand why this has come up only now, still working through that detail.

**Comment by ThisIsTheIC** [comment]
That seems to work @warrickball. Thanks so much.

**Comment by orionlee** [comment]
@scfleming Thanks for looking into it! So should we use `dataURI` for download in all cases, regardless on whether MAST would resurface `dataURL` or not?

Even that is the case, please keep us updated. If `dataURL` is permanently removed from MAST API, we might need to release a patch for the old `lightkurve` v1.x, in addition to the current v2.x

P.S. I recall some old correspondence on `dataURI` and `dataURL` for TASOC lightcurves (the values were different). The recommendation was to use `dataURI`. It looks like I dropped the ball on following it up.

**Comment by orionlee** [comment]
A correction: `lightkurve` actually uses `dataURL` for logging purpose only. The logging logic still causes the error nonetheless.

https://github.com/lightkurve/lightkurve/blob/4f2dbedb2d61e24348b43f36cfd3259f06d6d297/src/lightkurve/search.py#L351-L356

The actual download is done by astroquery's [`Observations.download_product()`](https://github.com/astropy/astroquery/blob/59cc72b10238a39ab2acfb09bb873c7934f1bcce/astroquery/mast/observations.py#L617-L619), which always uses `dataURI`.

**Comment by scfleming** [comment]
Quick update: we have identiied that this was the unexpected result of a change we made during the monthly patch. We'll be working on a fix to restore previous functionality.


Whether lightkurve should use `dataURI` or `dataURL` universally when looking at data product returns, and if so, the code changes to implement that can be treated as a separate lightkurve question. Some of the folks at MAST might be able to help confirm what the best practice should be.

**Comment by scfleming** [comment]
In terms of the latter question: best practice is to _always_ rely on `dataURI`. This is defined for every data product, and what you get after a `get_data_products()` query, for example.

The `dataURL` parameter is only available for the top-most (primary) product of an observation. It's a shortcut to check on or retrieve the primary product of an Observation without running a `get_data_products()` call. It works in some cases for datasets that lightkurve supports because some of them only have one product, but that is not the case generally.

I strongly recommend lightkurve get updated to retrieve all files using only the `dataURI` fields from a `get_data_products()`call, and not to rely on joining or using the `dataURL` from an `Observations.query_criteria()` search at the Observation level. I would not deem this an urgent issue, but it would make the codebase much more future-proof.

**Comment by orionlee** [comment]
Thanks Scott for looking into it from MAST angle.

A summary of the situation:
1. When MAST resolves the issue with the patch, the issue will be resolved for all existing `lightkurve` users.
2. @christinahedges  We should consider to release a patch for `lightkurve` nevertheless. See PR #1380
3. A clarification of the `lightkurve` bug: `lightkurve` misused `dataURL` in logging logic only. For the actual product download, the correct `dataURI` has been used via astroquery's [`Observations.download_product()`](https://github.com/astropy/astroquery/blob/59cc72b10238a39ab2acfb09bb873c7934f1bcce/astroquery/mast/observations.py#L617-L619).
