### ISSUE TITLE
`search_lightcurve(cadence="short")` includes FFI-based data for TESS sector 56+ / Cycle 5+

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1394]
#### Problem description

For `search_lightcurve(cadence="short")` would include various TESS FFI-based HLSP for sectors 56+, when FFI's exposure time is reduced to [200 seconds starting from cycle 5](https://heasarc.gsfc.nasa.gov/docs/tess/second-extended.html).

#### Example

```python
import lightkurve as lk
# insert code here ...

# pi Men
sr = lk.search_lightcurve("TIC261136679", mission="TESS", cadence="short")
print(sr)

```

SearchResult includes those based on 200 seconds FFIs:
```python
 #     mission     year   author  exptime target_name distance                proposal_id               
                                     s                 arcsec                                           
--- -------------- ---- --------- ------- ----------- -------- -----------------------------------------
  0 TESS Sector 04 2018      SPOC     120   261136679      0.0           G011183_G011132_G011048_G011250
  1 TESS Sector 01 2018      SPOC     120   261136679      0.0           G011183_G011132_G011048_G011250
...            ...  ...       ...     ...         ...      ...                                       ...
 18 TESS Sector 67 2023      SPOC     120   261136679      0.0                             G05144_G05155
 19 TESS Sector 62 2023 TESS-SPOC     200   261136679      0.0                                       N/A
 20 TESS Sector 61 2023 TESS-SPOC     200   261136679      0.0                                       N/A
 21 TESS Sector 66 2023       QLP     200   261136679      0.0                                       N/A
 22 TESS Sector 65 2023       QLP     200   261136679      0.0                                       N/A
...
```

#### Environment
-  lightkurve version (e.g. 1.0b6): 2.4.2

**Comment by orionlee** [comment]
One expedient way to fix it is to change the short cadence threshold from 300 seconds to 200 seconds. Would there be any unintended side effects?

https://github.com/lightkurve/lightkurve/blob/5e4c61975dd0c28bf4a5ee287aeb397137a74d3e/src/lightkurve/search.py#L1377-L1382

**Comment by Nschanche** [comment]
Hi @orionlee , good point. I tend to think people who use the 'short cadence' flag do actually want the postage stamp products, not FFI data. I will think on how we want to handle this. Thanks for the suggestion!

**Comment by orionlee** [comment]
BTW, the issue is also applicable to `search_targetpixelfile()`, because TESS-SPOC HLSP also releases TPFs, in addition to lightcurve files. For example,

```python
> print(lk.search_targetpixelfile("TIC261136679", mission="TESS", sector=61, cadence="short"))

#     mission     year   author  exptime target_name distance  proposal_id 
                                     s                 arcsec               
--- -------------- ---- --------- ------- ----------- -------- -------------
  0 TESS Sector 61 2023      SPOC     120   261136679      0.0 G05144_G05155
  1 TESS Sector 61 2023 TESS-SPOC     200   261136679      0.0           N/A
```

**Comment by Nschanche** [comment]
I've put in PR #1410 that implements this fix (ie, short cadence is now <200 rather than < 300 so that FFI data is not returned.
