### ISSUE TITLE
`centroid_quadratic()` incorrectly failed in a boundary case, when `mask` is specified and fluxes are all negative

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#1401]
#### Problem description

`lk.utils.centroid_quadratic()` would fail and return `(nan, nan)` in a specific boundary case:
- `mask` argument is specified, and
- the flux in `data` is all negative.

While all negative flux should not happen in normal flux data, they could possibly arise when the data is from a difference flux.

#### Example

See: https://gist.github.com/orionlee/fb9a855c3f4fe935ef653d72910768ac

#### Expected behavior

It should still return a reasonable centroid.

#### Environment

-  lightkurve version (e.g. 1.0b6): 2.4.2

**Comment by orionlee** [comment]
The root cause is when `mask` is specified, `centroid_quadratic()` sets flux of the masked pixels to 0.

https://github.com/lightkurve/lightkurve/blob/9dbb63433fcaa391f45a3fccda65d9ac1bb96340/src/lightkurve/utils.py#L632-L633

In the case where flux is all negative and `mask` is specified, the 3x3 patch chosen will all be the masked pixels, with uniform value of 0.

**Comment by Nschanche** [comment]
Hi @orionlee , thanks for the great notebook demonstrating the issue. I think this could be resolved with an extra step to ensure that 0 will not be the max location:

```
    if mask is not None:
        data = data * mask
    data_masked = data.copy()
    data_masked[data_masked == 0] = np.nan
    arg_data_max = np.nanargmax(data_masked)
'''

**Comment by Nschanche** [comment]
I've put in PR #1414, which sets the masked values to nan before identifying the pixel with max flux. This appears to work with the examples in the gist @orionlee provided.
