### ISSUE TITLE
The dependency 'astropy.config' doesn't work in lightkurve.

### ISSUE THREAD

**Issue by Roseane19** [lightkurve/lightkurve#1403]
#### Problem description

I was trying to install the module BoxLeastSquares from astropy.stats and wouldn't work. So I decided o make a upgrade in my astropy package using the command 'conda update astropy' in my anaconda prompt and it turns out the lightkurve package stopped working! I have got the following error in code:

#### Output:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[8], line 3
      1 get_ipython().run_line_magic('matplotlib', 'notebook')
      2 import matplotlib.pyplot as plt
----> 3 import lightkurve as lk
      4 import numpy as np

File ~\anaconda3\Lib\site-packages\lightkurve\__init__.py:49
     46 log = logging.getLogger(__name__)
     47 log.addHandler(logging.StreamHandler())
---> 49 from . import config as _config
     52 class Conf(_config.ConfigNamespace):
     53     """
     54     Configuration parameters for `lightkurve`.
     55 
   (...)
     72         If set to True, issue warning if the legacy default cache directory exists. Default is True.
     73     """

File ~\anaconda3\Lib\site-packages\lightkurve\config\__init__.py:4
      1 import os
      2 import warnings
----> 4 import astropy.config as astropyconfig
      7 ROOTNAME = 'lightkurve'
     10 class ConfigNamespace(astropyconfig.ConfigNamespace):

ModuleNotFoundError: No module named 'astropy.config'

#### Help:
How can I do fix this? I really appreciate if anyone could help me. Thanks!

#### Environment

-  platform : Windows; Jupyter Notebook (Anaconda)
-  lightkurve version: 2.4.2
-  astropy version: 6.0.0
-  installation method : python -m pip install lightkurve --upgrade; conda update astropy

**Comment by Nschanche** [comment]
Hi @Roseane19, I created a clean environment with astropy 6.0.0 and lightkurve 2.4.2 using Mac OS, and did not see a similar error. What version of Python are you using? You could you try creating a fresh environment with those packages and see if you have the same issue, or uninstalling/reinstalling lightkurve in your current environment. If you are still having problems I will try to debug on a windows machine.

**Comment by Roseane19** [comment]
Hi @Nschanche my python version is 3.11.5. I will follow you suggestion too, thanks!

**Comment by Nschanche** [comment]
Hi @Roseane19 were you able to resolve your issue with the new environment?

**Comment by Roseane19** [comment]
Hello @Nschanche. Actually, I could fix the code when I changed the version of the astropy from 6.0 to 5.3. 
Thanks for asking!
