### ISSUE TITLE
Lightkurve failed to find data in sector 83

### ISSUE THREAD

**Issue by keithini** [lightkurve/lightkurve#1409]
Running the python code:-

lk.search_lightcurve("347.45467 21.587974"radius=1)

returns the following:-

SearchResult containing 2 data products.

 #     mission     year   author  exptime target_name distance
                                     s                 arcsec 
--- -------------- ---- --------- ------- ----------- --------
  0 TESS Sector 56 2022      SPOC     120   436479963      0.0
  1 TESS Sector 56 2022 TESS-SPOC     200   436479963      0.0

However using TESS-point Web Tool (https://heasarc.gsfc.nasa.gov/wsgi-scripts/TESS/TESS-point_Web_Tool/TESS-point_Web_Tool/wtv_v2.0.py/) also shows data in sector 83:-

RA	Dec	EclipLong	EclipLat	Sector	Camera	CCD	ColPix	RowPix	Sector Midpoint
347.4547	21.588	357.5425	24.7027	56	1	1	1374.2608	1212.719	September 2022
347.4547	21.588	357.5425	24.7027	83	1	1	1747.7475	1217.351	September 2024

SO - the question is why lightkurve did not return sector 83 data.

Platform -windows 11
lightkurve version 2.4.2
installed using pip 

-  platform (e.g. Linux, OSX, Windows):
-  lightkurve version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):

**Comment by kirxkirx** [comment]
Sector 83 has not been observed yet, TESS is now around Sector 75. The real issue is that it's not obvious from the web tool or lk.search_lightcurve() output.

**Comment by keithini** [comment]
Hello Kirill

 

Many thanks for a quick response. I should have realised that sector 83 is in the future…   

 

Kind regards

 

Keith
