### ISSUE TITLE
.stitch() not working with LightCurveCollection

### ISSUE THREAD

**Issue by LordFurno** [lightkurve/lightkurve#1416]
#### Problem description

When using the .stitch() method on a lightcurvecollection, it results in the following error:
TypeError: 'MaskedQuantity' object with a scalar value is not iterable

#### Example

```python
import lightkurve as lk
# Search for Kepler observations of Kepler-69
search_result = lk.search_lightcurve('Kepler-69', author='Kepler', cadence='long')
# Download all available Kepler light curves
lc_collection = search_result.download_all()
lc=lc_collection.stitch()
```

#### Expected behavior

This should results in a stitched light curve.

#### Environment
I'm on windows, and used pip to install lightkurve.
I'm on lightkurve 2.3.0

**Comment by orionlee** [comment]
I cannot reproduce the issue in an environment with recent packages.

It is likely to be some bug / version incompatibility in astropy / numpy. See https://github.com/lightkurve/lightkurve/issues/1268#issuecomment-1383257739.


The environment:
```
lightkurve 2.4.2
astropy 6.0.0
Numpy 1.26.4
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:01:37) [MSC v.1935 64 bit (AMD64)]
```

**Comment by LordFurno** [comment]
I had to update astropy. Thank you!
