### ISSUE TITLE
Multi-planet system, bls.to_periodogram trouble getting different bits of data which i need

### ISSUE THREAD

**Issue by Brandon-D-J** [lightkurve/lightkurve#1418]
#### Problem description
Trying to do a multip-planet system, I see the points I need and where the exoplanets are potentially, but its on the collection bls.to_periodogram and I don't know how to do the further data analysis on the peaks that are smaller than the highest, plus there's 35 sectors of lightcurves and don't have the time to go through them all, is there any way to get these sections of peaks that are potential candidates from the one periodogram or away to get these peaks indivually.

#### Example
![image](https://github.com/lightkurve/lightkurve/assets/114146238/b4f61142-1416-4442-b48d-c59d2ecdc589)

#### Expected behavior
Just want to be able to access each of these peaks for data, if it doesn't work via this method to get the period and t0, what would be another way to do it?

#### Environment
on jupyter notebook windows, pip installed everything

**Comment by Nschanche** [comment]
Hi @Brandon-D-J , thanks for your comment. I'm not sure what you mean by just needing to access the peaks. The BLS object stores the power at each period, so you could create a mask based on the power values. For example, 
` mask = bls_col_hd.power > 75` to isolate values greater than 75, which looks reasonable given your plot or `mask = bls_col_hd.power > np.percentile(bls_col_hd, 99) ` to make a mask for values larger than the 99th percentile.
 
However, if you are looking for additional planets, it would be best to first subtract a model of the first planet's transits, then perform a new BLS to the residual data. This can be repeated until no further significant peaks in the BLS are found.

**Comment by Brandon-D-J** [comment]
Hi @Nschanche, thanks for getting back to me so quickly, I didn't even know I could do that, I tried googling it all and it didn't amount to anything. Would you be able to send me a guide or something that explains how to do the last bit you mentioned, because the data I'm using has 3 planets with a candidate 4 and I'm using the NASA archives to get the information, so being able to do that bit would greatly help me.

**Comment by Nschanche** [comment]
You can check out this [lightkurve tutorial](https://docs.lightkurve.org/tutorials/3-science-examples/exoplanets-identifying-transiting-planet-signals.html), which shows a simple version of completely masking out a planet and searching for additional signals. 
Alternatively, if you have a transit model (a model that is samples at the same time steps as the lightcurve data), you could instead subtract that model. Out-of-transit data points would remain the same, but the transits themselves would be removed, leaving any additional noise.

**Comment by Brandon-D-J** [comment]
ah, so that tutorial is explaining how to max out the most noticeable planet (in my example itd be the one at 56) and then the bls is created again with the 1st planet masked out so the next signal it finds is on only the remaining planets?

**Comment by Brandon-D-J** [comment]
Hi @Nschanche i've tried the tutorial and I've not been able to get a different value, it doesn't subtract for my data, when I then increase the period, it doesn't coincide with the published values of a period for the other planets, and I'm not that good at coding so I don't have any clue where to start with subtracting or even using the mask you mentioned before, I've tried plotting ti and it says there's an error where numpy.ndarray has no attribute plot, so I'm a little lost

**Comment by Nschanche** [comment]
Hi @Brandon-D-J I don't think this is a lightkurve issue, so I'm going to close this comment. However, you can email tesshelp@bigbang.gsfc.nasa.gov and we can help you further with this issue. If you reach out there, please include your a description of your goal and the code you are using so we can help address the issue you are having more clearly.

**Comment by Brandon-D-J** [comment]
Hi @Nschanche I've sent the email and explained it quite a bit, sorry it maybe long
