### ISSUE TITLE
Reading files wtih io.tess.read_tess_lightcurve(url) is filling astropy's cache directory

### ISSUE THREAD

**Issue by exo-pt** [lightkurve/lightkurve#1435]
#### Problem description
When reading lightcurves using **io.tess.read_tess_lightcurve(url)**, it would be useful to have the possibility of disabling caching.

The downloaded files are **kept on disk in Astropy's cache**, because astropy's fits.open() is called by lightkurve with (default) cache=True, and without a way to set it to False. 

With search_result().**download()**, I usually use, in windows, download_dir="/dev/null", but I don't see a way to disable cache in read_tess_lightcurve().

#### Expected behavior
It would be nice to have an option _cache=False_  affecting all lightkurve reads.
#### Environment

-  platform: Windows 11
-  lightkurve version: 2.4.2
-  astropy version:  5.3.4

**Comment by orionlee** [comment]
Not sure if it's a publicly-supported behavior, but a possible workaround is to pass astropy's HDUList to `read_tess_lightcurve()`, instead of the URL, so that one can explicitly controls caching

```python
with fits.open(url, cache=False) as hdul:
    lc = read_tess_lightcurve(hdul)
lc.scatter();
```

**Comment by exo-pt** [comment]
> 
> ```python
> with fits.open(url, cache=False) as hdul:
>     lc = read_tess_lightcurve(hdul)
> ```

That's an easy workaround indeed.

Anyway, I didn't expect a file "read by Lightkurve" to be cached in Astropy's cache
I only realized this, after checking the reason why my astropy's cache directory had more than 300Gb of files...

For my needs, the purposed workaround is enough. If the actual behaviour is accepta«ble, this issue can be closed.

Thank you

**Comment by exo-pt** [comment]
Accepted workaround
