### ISSUE TITLE
Users should be able to download products from STScI's cloud

### ISSUE THREAD

**Issue by snbianco** [lightkurve/lightkurve#1447]
#### Problem description
Astroquery allows users to download products directly from the cloud, and lightkurve is not making use of this currently.

**Comment by Nschanche** [comment]
Hi @snbianco, thanks for your message. We have been working on the new[ lksearch](https://github.com/lightkurve/lksearch/blob/main/docs/tutorials/cloud-data-searches.ipynb) package, which enables downloads directly from the cloud. I will close this comment for now, but please feel free to open it again if you have further comments on cloud downloads!
