### ISSUE TITLE
v2.5.0 release issues: missing in pypi, etc.

### ISSUE THREAD

**Issue by kecnry** [lightkurve/lightkurve#1459]
[v2.5.0](https://github.com/lightkurve/lightkurve/releases/tag/v2.5.0) was just recently released (thanks!) but is not showing up on [pypi](https://pypi.org/project/lightkurve/) (still lists 2.4.2 as the latest version).

**Comment by orionlee** [comment]
@tylerapritchard additional (to missing in pypi) issues for lightkurve v2.5.0 (
1. the package is not released in [conda](https://anaconda.org/conda-forge/lightkurve) either.
2. the version metadata in `lk.__version__` is incorrect: `2.5.0dev`

https://github.com/lightkurve/lightkurve/blob/f6c5f1e7eed684e8f525902778f62d429c8e3fad/src/lightkurve/version.py#L3

**Comment by tylerapritchard** [comment]
Thanks for pointing this out! I've updated the versioning and re-did the v.2.5.0 release, and @christinahedges  has pushed to pypi.  These should be updated and properly released on [pypi](https://pypi.org/project/lightkurve/) now, and so on conda-forge in a ~day hopefully.

**Comment by orionlee** [comment]
@tylerapritchard Thanks!

Also, after a release, `version.py` in `main` branch should be bumped to the next dev version, e.g., `'2.6.0dev'` or `'2.5.1dev'`
