### ISSUE TITLE
Target Pixel File cut-out example fails for TESS data

### ISSUE THREAD

**Issue by mommermi** [lightkurve/lightkurve#368]
I would like to extract Target Pixel Files from calibrated TESS FFI and tried running the [How to cut out Target Pixel Files from Kepler Superstamps or TESS FFIs?](http://docs.lightkurve.org/tutorials/cutting-out-tpfs-from-tess-ffis.html) example from the documentation but it fails. Using the exact syntax as provided in the example 

```
from lightkurve import KeplerTargetPixelFile
from astropy.coordinates import SkyCoord
tpf = KeplerTargetPixelFile.from_fits_images(images=fnames,
                                             position=SkyCoord(257.13700, 24.48958, unit='deg'),
                                             size=(9,9),
                                             target_id='MyCutOut')
```

leads to the following warning:

> .../site-packages/lightkurve/targetpixelfile.py:659: LightkurveWarning: A TESS data product is being opened using the `KeplerTargetPixelFile` class. Please use `TessTargetPixelFile` instead. 

The warning is triggered as part of `KeplerTargetPixelFile.from_fits_images`.  Unfortunately, the class `TessTargetPixelFile` does not have a method called `from_fits_images`. Will a TESS version of this method be available any time soon?

Run under Ubuntu 16.04, Python 3.6.4 (anaconda), lightkurve version 1.0b23, installed with pip.

**Comment by barentsen** [comment]
Thank you for reporting this issue @mommermi! You are quite right that the cut-out tool in the current version of Lightkurve hasn't fully been prepared for TESS yet.

I expect we will work on this over the coming month.  In meanwhile, you may be interested in trying MAST's new [astrocut package](https://astrocut.readthedocs.io/en/latest/) which is dedicated to this task.  This new tool also has an [online API called TESScut](https://mast.stsci.edu/tesscut/docs/index.html).
