### ISSUE TITLE
Periodogram.smooth() & .flatten() should belong to LombScarglePeriodogram()

### ISSUE THREAD

**Issue by ojhall94** [lightkurve/lightkurve#457]
It seems that during the partition of the Periodogram class into LombScarglePeriodogram and BoxLeastSquaredPeriodogram, the original flatten() and smooth() functions have been retained as functions of the overarching Periodogram class. This means that BLSPeriodogram inherits them, and consequently overwrites them with BLS-specific versions of these functions.

If these functions apply only to the LSPeriodogram, it seems to me that they should become functions of LSPeriodogram only.

This really isn't a big deal, just tidying. Thoughts?

**Comment by barentsen** [comment]
@ojhall94 Thanks for bringing this up!

Do you think we may have other Periodogram classes in the future that would use the same `flatten()` and `smooth()` implementations?  That would be the only reason to keep 'em there.  If not, I agree it is a bit tidier to move it to the sub-class!

**Comment by ojhall94** [comment]
I can't envision any, but then again all my pre-existing knowledge is already built in. I'll wait until #416 is merged before making any changes for this issue :)

**Comment by ojhall94** [comment]
Following a discussion at the Lightkurve Workshop at the CCA we decided to close this issue!
