### ISSUE TITLE
KeplerCBVCorrector should accept a KeplerLightCurve

### ISSUE THREAD

**Issue by christinahedges** [lightkurve/lightkurve#56]
Currently it does not and I want to correct my own light curve:

<img width="1125" alt="screen shot 2018-02-28 at 3 14 33 pm" src="https://user-images.githubusercontent.com/14965634/36818533-4c44cc5c-1c9a-11e8-88ae-7d038516c919.png">

**Comment by mirca** [comment]
We can safely close this as ``KeplerCBVCorrector`` doesn't exist anymore and the feature requested here has been implemented in the newer ``CBVCorrector`` class.
