### ISSUE TITLE
Flatten shouldn't automatically normalize

### ISSUE THREAD

**Issue by SimonJMurphy** [lightkurve/lightkurve#630]
#### Problem description
Currently, lc.flatten() will return a normalized light curve, but this isn't always desired.

#### Example

```python
from lightkurve import search_lightcurvefile
lcf = search_lightcurvefile("kic 6922244", quarter=4).download()
pdcsap = lcf.PDCSAP_FLUX
pdcsap.scatter() # makes scatter plot with y in electron counts per second
pdcsap.flatten().scatter() # makes scatter plot of flattened light curve but y is normalized.
```

#### Expected behavior
I expected a flattened light curve still in electron counts per second, but after flattening found that the lightcurve had also been normalized.

#### Environment

-  platform (e.g. Linux, OSX, Windows): OSX 10.14.6
-  lightkurve version (e.g. 1.0b6): 1.3.0
-  installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
Thanks @SimonJMurphy!  Without thinking about it too much, my initial response is that I agree :100:% with you.

@christinahedges @gully Do you want to weigh in?

**Comment by gully** [comment]
Yeah, I agree that flatten should just flatten!

**Comment by christinahedges** [comment]
I think I agree, I think there are some questions tho:

 1. Do we renormalize to the mean or the median?
 2. This is likely going to break a lot of code. Maybe there should be a keyword "normalize" that defaults to True?

**Comment by SimonJMurphy** [comment]
1. Actually, I was wondering whether the mean or the median is used. Maybe that should be a keyword to normalize(), that defaults to whatever is used now? For EBs/planets that’s an important distinction.
2. Definitely agree.


On 18 Nov 2019, at 16:55, Christina Hedges <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I agree, I think there are some questions tho:

  1.  Do we renormalize to the mean or the median?
  2.  This is likely going to break a lot of code. Maybe there should be a keyword "normalize" that defaults to True?

**Comment by IdaDixen** [comment]
If flatten should return a normalized light curve, the flux_unit should be updated too. Right now it is necessary to apply .normalize() either before or after flatten for the units to make sense in further analysis of the light curves.
