### ISSUE TITLE
Consistently use 'raw lightcurve'

### ISSUE THREAD

**Issue by mrtommyb** [lightkurve/lightkurve#708]
#### Problem description

In several tutorials the  phrase _raw light curve_ or _raw images_ is used to describe calibrated but not detrended data. This is not consistent with usage from Kepler or in the community.
Raw should on refer to data that has not been calibrated.

#### Example
e.g. [this page](https://docs.lightkurve.org/tutorials/04-how-to-remove-tess-scattered-light-using-regressioncorrector.html)

**Comment by barentsen** [comment]
@mrtommyb This is a fair comment!

I'm not sure what the right alternative word is. Should we call it "undetrended"? Or "uncorrected"? Or something else?

Opinions anyone?

**Comment by barentsen** [comment]
In our latest tutorials I've tried to make sure that we avoid the word "raw" when talking about calibrated-but-not-detrended data.  I will continue keep an eye on this.  Closing this issue for now!
