### ISSUE TITLE
An issue and a feature request with FoldedLightCurve

### ISSUE THREAD

**Issue by smoh** [lightkurve/lightkurve#741]
#### Problem description
- Slicing FoldedLightCurve does not slice `time_original` attribute. This attribute is not included in the `__getitem__` method in LightCurve class and never overwritten in FoldedLightCurve.

- Could we add `unfold` method to FoldedLightCurve? I sometimes find that it's easier to mask something out in a folded light curve but want to go back to the original time afterward. This seems easily implementable since `period` and `t0` is kept in FoldedLightCurve. 
(Edit: actually I guess we can just use time_original, duh)

#### Example

```python
import lightkurve

lc = lightkurve.LightCurve(np.linspace(0,100,101),np.zeros(101))
lc_folded = lc.fold(5)
mask = np.ones(101).astype(bool)
mask[[23,48,53,55,99]] = False   # masking some random cadences
lc_folded_sliced = lc_folded[mask]
print(lc_folded_sliced.time.size, lc_folded_sliced.flux.size, lc_folded_sliced.time_original.size)

# output
96 96 101

```

#### Expected behavior
Slicing something keeps everything sliced consistently.

#### Environment
I don't think this is environment-specific.

**Comment by rebekah9969** [comment]
Thank you very much for posting your issue. 
I am sorry that we did not get back to you sooner. 
Trying your example I see that the behavior is now as expected: 96 96 96

Lightkurve version: 2.4.0

**Comment by smoh** [comment]
Thanks for letting me know.
