### ISSUE TITLE
2.0 Upgrade compatibility - LightCurveFile.get_header() / header()

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#816]
#### Problem description
This is probably a specific case of the larger upgrade issue... I'm jotting it down just in case it gets lost.

In v1.x, to get metadata of a LightCurveFile, eg., TESS sector, one'd call
```python
  lightCurveFile.get_header()['SECTOR']
```

Currently, the equivalent for v2.0 alphas would be
```
  lightCurve.meta['sector']
```

I suppose we'd need to either
1. document it as a breaking change, or 
2. add compatibility methods in this case, to `LightCurve` class

#### Environment

-  lightkurve version (e.g. 1.0b6): `v2.0a2`

**Comment by barentsen** [comment]
Thanks @orionlee.  This is one of the breaking changes in Lightkurve v2.x.  Prior to releasing the first v2.0, we must make sure to have a well-advertised page in the docs explaining all these changes..

For now, the current list of breaking changes is here:
https://github.com/KeplerGO/lightkurve/pull/744#issue-422971937

If we wanted to add a compatibility method for this case, I guess we could define it as follows:
```python
def get_header():
    return self.meta
```
...do we think this method was sufficiently popular to require this?

**Comment by orionlee** [comment]
I don't have a strong opinion on whether we need compatibility methods.  In my use case, I use `'SECTOR', 'TSTART', 'TSTOP'` 

I have a feeling that compatibility methods are by and large unneeded, given there are many other (fundamental) breaking changes, e.g., `lc.time` to `lc.time.value` , `lc.flux` to `lc.flux.value`. 

I'll add a comment to #744 just so we don't forget.
