### ISSUE TITLE
LightCurve.time returns [1,2,3] regardless of expected values

### ISSUE THREAD

**Issue by mustaric** [lightkurve/lightkurve#950]
#### Problem description

I just checked out version 2.0b5 of lightkurve, and it seems to be breaking my code. I can't seem to use `.time` to get at the time column in a LightCurve object anymore when I create an object by hand.

#### Example
```
import lightkurve  as lk
import numpy as np

assert lk.__version__ == "2.0b5"
time = np.arange(100, 200, .5)
data = dict(time=time,
            flux= np.zeros_like(time)
        )

newObj = lk.LightCurve(data)
assert len(newObj['time']) == len(time)
assert len(newObj.time) == len(time)
```

#### Expected behavior
I expect both ways of accessing the time column to give the same result, a Time Quantity with 200 elements. Instead newObj.time returns `[1,2,3]`

#### Environment

-  platform OSX:
-  lightkurve version 2.0b5):
-  installation method source:

**Comment by barentsen** [comment]
@mustaric Thank you for opening an issue with a clear example! :pray: :+1:

I seem unable to reproduce this issue, i.e. `newObj.time` is a Time object containing 200 elements for me (see below).  The Lightkurve version you are using (2.0b5) is very recent and I am not aware of any changes that can explain this behavior.

Would you be willing to double-check if the issue occurs in a fresh kernel?  If so, could you let me know what versions of AstroPy and NumPy you are using?  Here are mine:

```python
>>> import astropy; print(astropy.__version__)
4.1
>>> import numpy; print(numpy.__version__)
1.19.5
```

Here is the value for `newObj.time` I obtain using your code:

```python
>>> newObj.time
<Time object: scale='tdb' format='jd' value=[100.  100.5 101.  101.5 102.  102.5 103.  103.5 104.  104.5 105.  105.5
 106.  106.5 107.  107.5 108.  108.5 109.  109.5 110.  110.5 111.  111.5
 112.  112.5 113.  113.5 114.  114.5 115.  115.5 116.  116.5 117.  117.5
 118.  118.5 119.  119.5 120.  120.5 121.  121.5 122.  122.5 123.  123.5
 124.  124.5 125.  125.5 126.  126.5 127.  127.5 128.  128.5 129.  129.5
 130.  130.5 131.  131.5 132.  132.5 133.  133.5 134.  134.5 135.  135.5
 136.  136.5 137.  137.5 138.  138.5 139.  139.5 140.  140.5 141.  141.5
 142.  142.5 143.  143.5 144.  144.5 145.  145.5 146.  146.5 147.  147.5
 148.  148.5 149.  149.5 150.  150.5 151.  151.5 152.  152.5 153.  153.5
 154.  154.5 155.  155.5 156.  156.5 157.  157.5 158.  158.5 159.  159.5
 160.  160.5 161.  161.5 162.  162.5 163.  163.5 164.  164.5 165.  165.5
 166.  166.5 167.  167.5 168.  168.5 169.  169.5 170.  170.5 171.  171.5
 172.  172.5 173.  173.5 174.  174.5 175.  175.5 176.  176.5 177.  177.5
 178.  178.5 179.  179.5 180.  180.5 181.  181.5 182.  182.5 183.  183.5
 184.  184.5 185.  185.5 186.  186.5 187.  187.5 188.  188.5 189.  189.5
 190.  190.5 191.  191.5 192.  192.5 193.  193.5 194.  194.5 195.  195.5
 196.  196.5 197.  197.5 198.  198.5 199.  199.5]>
```

**Comment by mustaric** [comment]
Hi @barentsen,
  It looks like I had somehow gotten my imports into a weird inconsistent state, surprising because I was getting this after importing only lightkurve and sys. I think it resulted somehow from how I was adding the path to the location of the github clone of lightkurve or importing lightkurve more than once. 
   Since reporting this, I have reopened Spyder and the iPython terminal I was running and cannot reproduce the issue.  So I'd say close this issue. My apologies for wasting your time.

**Comment by barentsen** [comment]
No need to apologize, opening issues is a good thing!  If anyone else encounters this strange issue they'll be able to find this thread for reference.

I am happy it does not appear to be an embarrassing bug in Lightkurve =)
