### ISSUE TITLE
LightCurveCollection.plot() doesn't work well for different pipelines

### ISSUE THREAD

**Issue by barentsen** [lightkurve/lightkurve#958]
When plotting SPOC and QLP light curves together using the following example:
```python
import lightkurve as lk
lk.search_lightcurve('TIC 1717079071', sector=26, radius=0.0001).download_all().plot()
```

The Y label says "Normalized Flux" based on the QLP light curve, but this label is incorrect because the plot also includes SPOC light curves in units electron/sec.  A likely solution is to issue a warning that reads: `"You are plotting light curves that have different units (normalized, electron/s).  We recommend using `normalize=True` to bring them on the same scale."`

A second issue is that creating the plot using `.plot(normalize=True, offset=0.1)` doesn't yield a good result because the offset is only applied to light curves with different target names.  A better mechanism to apply the offsets is needed.

**Comment by Nschanche** [comment]
Just tested this and it appears both of these changes have already been implemented in the current lightkurve version. Closing the issue.
