### ISSUE TITLE
LightkurveDeprecationWarning: The SAP_FLUX function is deprecated

### ISSUE THREAD

**Issue by pllim** [lightkurve/lightkurve#987]
#### Problem description

Upgrading from 1.x to 2.x gives this deprecation warning:

```python
from lightkurve import search_lightcurve
lcf = search_lightcurve("Kepler-8", quarter=4, mission="Kepler", exptime=1800).download()
lc = lcf.SAP_FLUX.remove_nans().remove_outliers()  # Deprecation warning
```

```
lightkurve.utils.LightkurveDeprecationWarning: The SAP_FLUX function
is deprecated and may be removed in a future version.
```

This is after fixing #986 and while the warning looks similar to #985 ,  the code is different enough that I cannot apply the suggestion there.

**Comment by barentsen** [comment]
Selecting `sap_flux` light curves is now done by passing `flux_column="sap_flux"` to the `download()` or `read()` functions.

In your example, the solution is as follows:

```python
from lightkurve import search_lightcurve
search = search_lightcurve("Kepler-8", quarter=4, mission="Kepler", exptime=1800)
lc = search.download(flux_column="sap_flux")
lc = lc.remove_nans().remove_outliers()
```

I hope this helps!

**Comment by pllim** [comment]
Yes, it does. Can't say it is completely backward compatible, but your answer solves the original question. Thanks!

```python
flat = lc.flatten(window_length=81)
flat.flux  # is now a Quantity
```

**Comment by barentsen** [comment]
Right, `lc.flux` is now always a Quantity.

Lightkurve v2 is definitely not 100% backwards compatible!
