### ISSUE TITLE
Different light curves from lightkurve and archive data

### ISSUE THREAD

**Issue by vvinuv** [lightkurve/lightkurve#989]
I am new to Kepler data and I have an issue with Kepler light curve

#### Problem description
I would like to get light curves for eclipsing binaries. I directly downloaded the light curve from Kepler data archive (https://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/EclipsingBinaries/) and it has SAP_FLUX and PDCSAP_FLUX. I also downloaded Kepler Target Pixel File for one of those objects 
(wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/kepler/target_pixel_files/0089/008912468/kplr008912468-2010078095331_lpd-targ.fits.gz) and got light curve using lightkurve. I read from https://docs.lightkurve.org/tutorials/1-getting-started/using-light-curve-file-products.html that "By default, a KeplerLightCurve will set the PDCSAP flux to its .flux property".  I suppose that the above statement is also true for the light curve estimated from Kepler target pixel. However, the light curve from lightkurve (.flux) and the archival light curves (.PDCSAP_FLUX) don't agree. 

#### Example

```python
import lightkurve
# Light curve from lightkurve
tpf = KeplerTargetPixelFile('kplr008912468-2010078095331_lpd-targ.fits.gz')
tpf.to_lightcurve(aperture_mask=tpf.pipeline_mask).plot()
lc_flux = tpf.to_lightcurve(aperture_mask=tpf.pipeline_mask).flux

# Light curve from archive 
lc = lk.search.open('lc_8912468_Q4.fits')
lc.get_lightcurve('PDCSAP_FLUX').plot()
lc_PDCSAP = lc.PDCSAP_FLUX.flux

```

#### Expected behavior
I expect that the lc_flux and lc_PDCSAP are the same.

#### Environment

-  platform (e.g. Linux, OSX, Windows): OSX
-  lightkurve version (e.g. 1.0b6): 1.11.3
-  installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
@vvinuv Thank you for getting in touch and posting a nice example.  You identified an aspect of Kepler data analysis that can definitely be confusing!

The `lc_flux` in your example corresponds to the SAP_FLUX column in the light curve file, because it is a simple sum of the pixel values in the Target Pixel File. (Kepler people refer to this sum as "Simple Aperture Photometry", i.e. SAP).

To reproduce PDCSAP_FLUX, additional corrections need to be applied to remove instrument noise.   The "PDC" acronym refers to a module in the official Kepler pipeline ("Presearch Data Conditioning") which takes care of removing noise.

Unfortunately we do not have a robust "PDC" module in Lightkurve yet.  This explains why the `tpf.to_lightcurve()` does not attempt to apply an automated correction, i.e. why it does not reproduce PDCSAP_FLUX at this time.

We recently added a new feature ("CBVCorrector", see [tutorial here](https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-3-how-to-use-cbvcorrector.html)) which is an effort to attempt to replicate what the PDC module of the official pipeline does. Hopefully it will become fast and robust enough in the future that we could have `tpf.to_lightcurve()` apply this by default.

I hope this helps.  Do respond below if you have additional questions!

**Comment by vvinuv** [comment]
Thank you @barentsen. However, the SAP_FLUX from the archival data is also not agreeing with lightkurve flux. I did the following

```

# Light curve from lightkurve
tpf = KeplerTargetPixelFile('kplr008912468-2010078095331_lpd-targ.fits.gz')
tpf.to_lightcurve(aperture_mask=tpf.pipeline_mask).plot()
lc_flux = tpf.to_lightcurve(aperture_mask=tpf.pipeline_mask).flux
lc_flux_bkg = lc_flux + tpf.get_bkg_lightcurve().flux

# Light curve from archive 
lc = lk.search.open('lc_8912468_Q4.fits')
lc.get_lightcurve('SAP_FLUX').plot()
lc_SAP = lc.SAP_FLUX.flux

```

lc_SAP agrees neither with lc_flux or lc_flux_bkg.

**Comment by barentsen** [comment]
Thanks for reporting this @vvinuv. 🙏  This deserves some more investigation.

@rebekah9969 Would you be willing to look into this after the weekend?

**Comment by rebekah9969** [comment]
Hello @vvinuv 
Thank you for your query. 
Would you try the following for me please - note that I am using lightkurve v2.0

`import lightkurve as lk
# Light curve from TPF search
tpf = lk.KeplerTargetPixelFile('kplr008912468-2010078095331_lpd-targ.fits')
sap_lc = tpf.to_lightcurve(aperture_mask=tpf.pipeline_mask)'

This collects the data from the target pixel file  - the flux here is SAP

`search = lk.search_lightcurve('KIC 8912468', mission="Kepler", quarter=4)
lc = search.download()`

This collects the lightcurve file data from the archive - there is PDCSAP and SAP flux in this file

Now lets plot the SAP flux from both, 

`ax = sap_lc.plot(label="TPF SAP")
lc.plot(column='sap_flux', label="LCF SAP", ax=ax)`

This should produce the plot attached.
<img width="817" alt="Screen Shot 2021-03-01 at 12 35 37 PM" src="https://user-images.githubusercontent.com/17503131/109535534-af4bfb80-7a8a-11eb-9c20-bc0e638b18b5.png">

As you can see the SAP flux from the TPF and the light curve file are the same. 

If you apply this code do you get the same?
Thank you

**Comment by vvinuv** [comment]
That is great @rebekah9969! I can also produce this figure with v2. However, the fluxes of those light curves are not agreeing when I print it. I checked the time of light curve points and those are similar. Could you please let me know why this happens?  Also, `lc` doesn't provide any function for background estimation. 


`search = lk.search_lightcurve('KIC 8912468', mission="Kepler", quarter=4)`
`lc = search.download()`
`print('Flux:', lc.flux[:10])`
`print('Time' lc.time[:10])`



Flux: [nan 289874.   290318.8  289145.16 290448.56 289206.7  290132.06
 289674.44 289647.28 290151.1 ] electron / s 
Time: [352.37716372 352.39759652 352.43846211 352.4588949  352.4793277
 352.4997605  352.52019329 352.54062599 352.56105889 352.58149168]


`tpf = KeplerTargetPixelFile('EclipsingBinary/kplr008912468-2010078095331_lpd-targ.fits.gz')`
`sap_lc = tpf.to_lightcurve(aperture_mask=tpf.pipeline_mask)`
`print('Flux:', sap_lc.flux[:10])`
`print('Time:', sap_lc.time[:10])`


Flux: [282176.28 282030.3  282453.94 281372.88 282592.16 281397.8  282309.62
 281852.66 281799.72 282330.8 ] electron / s 
Time: [352.37716372 352.39759652 352.43846211 352.4588949  352.4793277
 352.4997605  352.52019329 352.54062599 352.56105889 352.58149168]

**Comment by rebekah9969** [comment]
Hello @vvinuv, 

In this case the comparison code that you need is, 

`print('Flux', lc.sap_flux[:10])
print('Time', lc.time[:10])`

and 

`print('Flux:', sap_lc.flux[:10])
print('Time:', sap_lc.time[:10])`

Remember the light curve files default the flux to the pdcsap flux, not the sap. 

I hope that this helps. 

Thanks

**Comment by vvinuv** [comment]
Thank you @rebekah9969. This definitely helps.

**Comment by barentsen** [comment]
Thanks @rebekah9969! :+1:

**Comment by vvinuv** [comment]
One more issue is in the analysis of light curve data. I am not able to do flattening of SAP_FLUX from the archival light curve data. Here is I do it

`search = lk.search_lightcurve('KIC 8912468', mission="Kepler", quarter=4)`
`lc = search.download()`
`lc.flatten(window_length=51)['flux', 'sap_flux']`

    flux         sap_flux   
    electron / s   electron / s 
    float64        float32    
    -------------- --------------
           nan  2.8217631e+05
    1.0001871e+00  2.8203028e+05
    1.0017157e+00  2.8245394e+05
    9.9766033e-01  2.8137288e+05
    etc

`flux` parameter  gets flattened but `sap_flux` is not.

**Comment by barentsen** [comment]
@vvinuv Thanks for reporting this!

It is correct that the `flatten()` method only alters the values of the `flux` column.

In order to flatten the `sap_flux` data, you'd have to make sure that this data is loaded into the `flux` column`, either using:

```
lc = search.download(flux_column="sap_flux")
```

or, alternatively:

```
lc['flux'] = lc['sap_flux']
lc['flux_err'] = lc['sap_flux_err']
```

Does that help?

**Comment by vvinuv** [comment]
@barentsen It definitely helps. However, it would be better if someone can access the flattening values of all the fluxes. Otherwise it takes another additional calculation.
